//
//  HakoPowerReportDetailView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/HakoPowerReportDetailView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

@MainActor
public struct HakoPowerReportDetailView: View {
    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var environments: ExtensionEnvironments

    @State private var alert: AlertState?
    @State private var files: [PowerReportFile] = []
    @State private var isLoading = true


        @State private var exportDocument: ReportZipDocument?
        @State private var showExporter = false
        @State private var sharePopupPresented = false
        @State private var includeConfig = false
        @State private var includeLog = false
        @State private var useAgeEncryption = false
        @State private var pendingAction: ReportShareAction?


    let report: PowerReport

    public init(report: PowerReport) {
        self.report = report
    }

    private var manager: PowerReportManager {
        environments.powerReportManager
    }


        private func saveReport(includeConfig: Bool, includeLog: Bool, useAgeEncryption: Bool) async {
            do {
                let zipURL = try await createReportZip(
                    reportID: report.id, fileURL: report.fileURL,
                    cacheSubdirectory: ReportType.power.directoryName, includeConfig: includeConfig, includeLog: includeLog,
                    encrypt: useAgeEncryption
                )
                exportDocument = HakoReportZipDocument(url: zipURL)
                showExporter = true
            } catch {
                alert = AlertState(action: "save power report", error: error)
            }
        }

        private func shareReport(includeConfig: Bool, includeLog: Bool, useAgeEncryption: Bool) async {
            do {
                let zipURL = try await createReportZip(
                    reportID: report.id, fileURL: report.fileURL,
                    cacheSubdirectory: ReportType.power.directoryName, includeConfig: includeConfig, includeLog: includeLog,
                    encrypt: useAgeEncryption
                )

                    presentShareSheet(zipURL)


            } catch {
                alert = AlertState(action: "export power report", error: error)
            }
        }


    public var body: some View {
        // The report read views were a `FormView` plus a separate chrome call. The
        // report scaffold is the same page - the system grouped form and the shared
        // chrome - with the page canvas, the empty and loading conventions and one
        // place that decides all of it.
        HakoReportScaffold(title: report.date.formatted(date: .abbreviated, time: .shortened)) {
            if !isLoading, !files.isEmpty {
                Section("Files") {
                    ForEach(files) { file in
                        if file.kind == .metadata {
                            FormNavigationLink {
                                MetadataFormView(url: file.fileURL, title: file.displayName)
                            } label: {
                                Text(file.displayName)
                            }
                        } else if file.kind == .configContent || file.kind == .timeline || file.kind == .events || file.kind == .goLog {
                            FormNavigationLink {
                                HakoReportFileContentView(fileURL: file.fileURL, displayName: file.displayName)
                            } label: {
                                Text(file.displayName)
                            }
                            .accessibilityIdentifier("hako.report.file")
                        } else {
                            Text(file.displayName)
                        }
                    }
                }
            }
        }
        .overlay {
            if isLoading {
                ProgressView()
            } else if files.isEmpty {
                HakoEmptyState(
                    symbol: "doc.text",
                    title: "Empty",
                    message: "This report has no content."
                )
            }
        }
        .onAppear {
            Task {
                files = await manager.availableFiles(for: report)
                manager.markAsRead(report)
                isLoading = false
            }
        }
        .alert($alert)

            .fileExporter(
                isPresented: $showExporter,
                document: exportDocument,
                contentType: useAgeEncryption ? .data : .zip,
                defaultFilename: useAgeEncryption ? "\(report.id).zip.age" : "\(report.id).zip"
            ) { result in
                exportDocument = nil
                if case let .failure(error) = result {
                    alert = AlertState(action: "save power report", error: error)
                }
            }
            .sheet(isPresented: $sharePopupPresented, onDismiss: {
                let action = pendingAction
                pendingAction = nil
                switch action {
                case .save:
                    Task { await saveReport(includeConfig: includeConfig, includeLog: includeLog, useAgeEncryption: useAgeEncryption) }
                case .share:
                    Task { await shareReport(includeConfig: includeConfig, includeLog: includeLog, useAgeEncryption: useAgeEncryption) }
                case .none:
                    break
                }
            }) {
                HakoReportSharePopup(
                    hasConfig: files.contains(where: { $0.kind == .configContent }),
                    hasLog: files.contains(where: { $0.kind == .goLog }),
                    includeConfig: $includeConfig,
                    includeLog: $includeLog,
                    useAgeEncryption: $useAgeEncryption,
                    onSave: { pendingAction = .save },
                    onShare: { pendingAction = .share }
                )
            }


        .toolbar {
            if !isLoading, !files.isEmpty {


                    Button {
                        includeConfig = false
                        includeLog = false
                        useAgeEncryption = false
                        sharePopupPresented = true
                    } label: {
                        Label("Share", systemImage: "square.and.arrow.up")
                    }
                    Button(role: .destructive) {
                        Task {
                            await manager.delete(report)
                            dismiss()
                        }
                    } label: {
                        Label("Delete", systemImage: "trash.fill")
                            .foregroundStyle(.red)
                    }
                    .tint(.red)

            }
        }
    }
}
