//
//  HakoOutboundPickerView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/OutboundPickerView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI

@MainActor
public protocol HakoOutboundSelectable: ObservableObject {
    var selectedOutbound: String { get set }
    var isRunning: Bool { get }
    func cancel()
}

public struct HakoToolOutboundSection<VM: HakoOutboundSelectable>: View {
    @ObservedObject var profile: ExtensionProfile
    @ObservedObject var viewModel: VM

    public var body: some View {
        Group {
            if profile.status.isConnectedStrict {
                OutboundPickerLink(viewModel: viewModel)
            }
        }
        .onChangeCompat(of: profile.status) { status in
            if !status.isConnectedStrict {
                if viewModel.isRunning {
                    viewModel.cancel()
                }
                viewModel.selectedOutbound = ""
            }
        }
    }
}

public struct HakoRemoteToolOutboundSection<VM: HakoOutboundSelectable>: View {
    @ObservedObject var commandClient: CommandClient
    @ObservedObject var viewModel: VM

    public init(commandClient: CommandClient, viewModel: VM) {
        _commandClient = ObservedObject(wrappedValue: commandClient)
        _viewModel = ObservedObject(wrappedValue: viewModel)
    }

    public var body: some View {
        Group {
            if commandClient.isConnected {
                OutboundPickerLink(viewModel: viewModel)
            }
        }
        .onChangeCompat(of: commandClient.isConnected) { isConnected in
            if !isConnected {
                if viewModel.isRunning {
                    viewModel.cancel()
                }
                viewModel.selectedOutbound = ""
            }
        }
    }
}

private struct OutboundPickerLink<VM: HakoOutboundSelectable>: View {
    @ObservedObject var viewModel: VM

    var body: some View {
        FormNavigationLink {
            HakoOutboundPickerView(selectedOutbound: $viewModel.selectedOutbound)
        } label: {
            HStack {
                Text("Outbound")
                Spacer()
                Text(viewModel.selectedOutbound.isEmpty ? String(localized: "Default") : viewModel.selectedOutbound)
                    .foregroundColor(.secondary)
                    .lineLimit(1)
            }
        }
    }
}

@MainActor
public struct HakoOutboundPickerView: View {
    @Binding var selectedOutbound: String
    @StateObject private var commandClient = CommandClient(.outbounds)
    @State private var outbounds: [OutboundGroupItem] = []
    @State private var searchText = ""
    @Environment(\.dismiss) private var dismiss

    private var filteredOutbounds: [OutboundGroupItem] {
        if searchText.isEmpty {
            return outbounds
        }
        return outbounds.filter { $0.tag.localizedCaseInsensitiveContains(searchText) }
    }

    public var body: some View {
        List {
            Button {
                selectedOutbound = ""
                dismiss()
            } label: {
                HStack(spacing: HakoTheme.Spacing.compact) {
                    Text("Default")
                        .foregroundStyle(.foreground)
                    Spacer(minLength: HakoTheme.Spacing.compact)
                    HakoSelectionMark(isSelected: selectedOutbound.isEmpty)
                }
                .contentShape(Rectangle())
            }


            ForEach(filteredOutbounds, id: \.tag) { item in
                Button {
                    selectedOutbound = item.tag
                    dismiss()
                } label: {
                    HStack(spacing: HakoTheme.Spacing.compact) {
                        VStack(alignment: .leading, spacing: HakoTheme.Spacing.tight) {
                            Text(item.tag)
                                .foregroundStyle(.foreground)
                                .lineLimit(1)
                            HStack(spacing: HakoTheme.Spacing.tight) {
                                Text(item.displayType)
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                                Spacer(minLength: 0)
                                if item.urlTestDelay > 0 {
                                    Text(item.delayString)
                                        .font(.caption.monospacedDigit())
                                        .foregroundColor(item.delayColor)
                                }
                            }
                        }
                        HakoSelectionMark(isSelected: selectedOutbound == item.tag)
                    }
                    .contentShape(Rectangle())
                }


            }
        }

        .searchable(text: $searchText, placement: .navigationBarDrawer(displayMode: .always))


        .navigationTitle("Outbound")
        .onAppear {
            commandClient.connect()
        }
        .onDisappear {
            commandClient.disconnect()
        }
        .onReceive(commandClient.$outbounds) { goOutbounds in
            guard let goOutbounds else { return }
            outbounds = goOutbounds.map { OutboundGroupItem($0) }
        }
    }
}
