//
//  HakoOOMReportListView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/OOMReportListView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI

@MainActor
public struct HakoOOMReportListView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @State private var isLoading = true


    public init() {}

    private var manager: OOMReportManager {
        environments.oomReportManager
    }

    public var body: some View {
        HakoReportScaffold(title: String(localized: "Out of Memory Report")) {
            if !isLoading {
                HakoSettingsSection("Reports", footnote: "A report is recorded when the device runs out of memory while the service is running.") {
                    if manager.reports.isEmpty {
                        HakoCardEmptyState(
                            symbol: "memorychip",
                            title: "No memory reports",
                            message: "Reports recorded when the device ran out of memory appear here."
                        )
                        .frame(minHeight: 180)
                    } else {
                        ForEach(manager.reports) { report in


                                FormNavigationLink {
                                    HakoOOMReportDetailView(report: report)
                                } label: {
                                    reportLabel(report)
                                }
                                // The report's own identifier, as the crash list's rows have:
                                // a test can address the row rather than guess at it by position.
                                .accessibilityIdentifier("hako.report.\(report.id)")

                        }
                    }
                }


            }
        }
        .overlay {
            if isLoading {
                ProgressView()
            }
        }
        .onAppear {
            Task {
                await manager.refresh()


                isLoading = false
            }
        }


        .toolbar {


                ToolbarItem {
                    OOMReportToolbarMenu(manager: manager, profile: environments.extensionProfile)
                }

        }
    }

    private func reportLabel(_ report: OOMReport) -> some View {
        // The original's own two-arm condition, restored: `ReportLabel` is the tvOS arm and the
        // navigation row is every other platform's. Collapsing it removed the only caller the
        // ported `HakoReportLabel` ever had, which left it declared and unreachable.
        #if os(tvOS)
            HakoReportLabel(date: report.date, isRead: report.isRead, origin: report.origin)
        #else
            HakoNavigationRow(
                title: report.date.formatted(date: .abbreviated, time: .shortened),
                subtitle: report.origin == ReportArchive.tvOSDeviceOrigin
                    ? String(localized: "From Apple TV")
                    : String(localized: "From this device"),
                systemImage: "memorychip",
                tint: HakoAccentRole.neutral.color,
                badge: report.isRead ? nil : String(localized: "Unread"),
                badgeEmphasis: .info
            )
        #endif

    }


}


    private struct OOMReportToolbarMenu: View {
        @ObservedObject var manager: OOMReportManager
        let profile: ExtensionProfile?
        @State private var alert: AlertState?

        var body: some View {
            if profile != nil || !manager.reports.isEmpty {
                Menu {
                    if let profile {
                        Button {
                            triggerOOMReport(profile: profile, manager: manager, alert: &alert)
                        } label: {
                            Label("Fetch Memory Report", systemImage: "memorychip")
                        }
                    }
                    if !manager.reports.isEmpty {
                        Button(role: .destructive) {
                            Task {
                                await manager.deleteAll()
                            }
                        } label: {
                            Label("Delete All", systemImage: "trash.fill")
                        }
                    }
                } label: {
                    Label("Others", systemImage: "line.3.horizontal.circle")
                }
                .alert($alert)
            }
        }
    }


@MainActor
private func triggerOOMReport(profile: ExtensionProfile, manager: OOMReportManager, alert: inout AlertState?) {
    guard profile.status.isConnectedStrict else {
        alert = AlertState(errorMessage: String(localized: "Service not started"))
        return
    }
    do {
        try LibboxNewStandaloneCommandClient()?.triggerOOMReport()
    } catch {
        alert = AlertState(action: "trigger OOM report", error: error)
        return
    }
    Task {
        try? await Task.sleep(nanoseconds: NSEC_PER_SEC)
        await manager.refresh()
    }
}
