//
//  HakoNewProfileView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Profile/HakoNewProfileView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Foundation
import Libbox
import Library
import SwiftUI

@MainActor
public struct HakoNewProfileView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @Environment(\.dismiss) private var dismiss
    @StateObject private var viewModel: NewProfileViewModel
    private var onSuccess: ((Profile) async -> Void)?

    public struct HakoImportRequest: Codable, Hashable, Identifiable {
        public var id: String {
            url
        }

        public let name: String
        public let url: String
    }

    public struct HakoLocalImportRequest: Hashable, Identifiable {
        public var id: String {
            fileURL.absoluteString
        }

        public let name: String
        public let fileURL: URL

        public init(name: String, fileURL: URL) {
            self.name = name
            self.fileURL = fileURL
        }
    }

    public init(
        _ importRequest: HakoImportRequest? = nil,
        localImportRequest: HakoLocalImportRequest? = nil,
        onSuccess: ((Profile) async -> Void)? = nil
    ) {
        _viewModel = StateObject(wrappedValue: NewProfileViewModel(importRequest: importRequest, localImportRequest: localImportRequest))
        self.onSuccess = onSuccess
    }

    public var body: some View {


            iOSBody

    }

    private static var profileTypeOptions: [FormPickerOption<ProfileType>] {
        var options = [FormPickerOption(ProfileType.local, String(localized: "Local"))]

            options.append(FormPickerOption(ProfileType.icloud, String(localized: "iCloud")))

        options.append(FormPickerOption(ProfileType.remote, String(localized: "Remote")))
        return options
    }

    private static var fileImportOptions: [FormPickerOption<Bool>] {
        [
            FormPickerOption(false, String(localized: "Create New")),
            FormPickerOption(true, String(localized: "Import")),
        ]
    }

    private var ownsDismiss: Bool {


            true

    }

    private var formContent: some View {
        FormView {
            Section {
                FormItem(String(localized: "Name")) {
                    TextField("Name", text: $viewModel.profileName, prompt: Text("Required"))
                        .multilineTextAlignment(.trailing)
                }
                FormPicker(String(localized: "Type"), options: Self.profileTypeOptions, selection: $viewModel.profileType)
                if viewModel.profileType == .local {
                    FormPicker(String(localized: "File"), options: Self.fileImportOptions, selection: $viewModel.fileImport)


                    Group {
                        if viewModel.fileImport {
                            HStack {
                                Text("File Path")
                                Spacer()
                                Spacer()
                                if let fileURL = viewModel.fileURL {
                                    Button(fileURL.fileName) {
                                        viewModel.pickerPresented = true
                                    }
                                } else {
                                    Button("Choose") {
                                        viewModel.pickerPresented = true
                                    }
                                }
                            }
                        }
                    }
                } else if viewModel.profileType == .icloud {
                    FormItem(String(localized: "Path")) {
                        TextField("Path", text: $viewModel.remotePath, prompt: Text("Required"))
                            .multilineTextAlignment(.trailing)
                    }
                } else if viewModel.profileType == .remote {
                    FormItem(String(localized: "URL")) {
                        TextField("URL", text: $viewModel.remotePath, prompt: Text("Required"))
                            .multilineTextAlignment(.trailing)

                            .keyboardType(.URL)

                    }
                    Toggle("Auto Update", isOn: $viewModel.autoUpdate)
                    FormItem(String(localized: "Auto Update Interval")) {
                        TextField("Auto Update Interval", text: $viewModel.autoUpdateInterval.stringBinding(defaultValue: 60), prompt: Text("In Minutes"))
                            .multilineTextAlignment(.trailing)

                            .keyboardType(.numberPad)

                    }
                }
            } footer: {
                if viewModel.profileType == .icloud {
                    let fileName = viewModel.remotePath.isEmpty ? String(localized: "FileName") : viewModel.remotePath
                    Text("File will be located at iCloud Drive/sing-box/\(fileName)")
                }
            }

                // No card: the review asked for the primary button to sit on the page's own
                // background rather than inside a white row that exists only to hold it.
                Section {
                    if !viewModel.isSaving {
                        FormButton {
                            viewModel.isSaving = true
                            Task {
                                await viewModel.createProfile(
                                    environments: environments,
                                    dismiss: ownsDismiss ? dismiss : nil,
                                    onSuccess: onSuccess
                                )
                            }
                        } label: {
                            // The title centred in the button, the glyph beside it rather than in
                            // front of it: a `Label` centres glyph and text as one unit, which
                            // puts the words right of the button's centre - the review's "the
                            // Create text must be truly centred in the clickable area".
                            Text("Create")
                                .frame(maxWidth: .infinity)
                                .overlay(alignment: .leading) {
                                    Image(systemName: "doc.fill.badge.plus")
                                }
                        }
                        // The page's primary action, in the design system's primary treatment.
                        // `FormButton` is a bare button on the touch platforms, so this was a
                        // blue text row while every other primary action in the client is a
                        // filled one - the review's "the Create button must use the global
                        // primary style".
                        .hakoPrimaryActionButtonStyle()
                        .controlSize(.large)
                        .listRowBackground(Color.clear)
                        .listRowInsets(EdgeInsets())
                    } else {
                        ProgressView()
                            .listRowBackground(Color.clear)
                    }
                }

        }
    }


        private var iOSBody: some View {
            formContent
                .disabled(viewModel.isSaving)
                .alert($viewModel.alert)
                .onChangeCompat(of: viewModel.createSucceeded) { newValue in
                    if newValue, ownsDismiss {
                        dismiss()
                    }
                }

                .fileImporter(
                    isPresented: $viewModel.pickerPresented,
                    allowedContentTypes: [.json],
                    allowsMultipleSelection: false
                ) { result in
                    do {
                        let urls = try result.get()
                        if !urls.isEmpty {
                            viewModel.fileURL = urls[0]
                        }
                    } catch {
                        viewModel.alert = AlertState(action: "read imported profile file", error: error)
                        return
                    }
                }

        }

}
