//
//  HakoCrashReportDetailView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/CrashReportDetailView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

@MainActor
public struct HakoCrashReportDetailView: View {
    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var environments: ExtensionEnvironments

    @State private var alert: AlertState?
    @State private var files: [CrashReportFile] = []
    @State private var isLoading = true


        @State private var exportDocument: HakoReportZipDocument?
        @State private var showExporter = false
        @State private var sharePopupPresented = false
        @State private var includeConfig = false
        @State private var includeLog = true
        @State private var useAgeEncryption = false
        // `#if !os(tvOS)`, as the original has it: `HakoReportShareAction` is declared under that condition in
    // `ApplicationLibrary/Views/Tools/ReportShared.swift:135`, and only the share sheet above reads this.
    #if !os(tvOS)
        @State private var pendingAction: HakoReportShareAction?
        // The macOS share path, as the original has it. `presentShareSheet` is declared under
        // `#if os(iOS)` in `Tools/ReportShared.swift`, so the Mac needs its own way to present the
        // file - see `SharingServicePicker` below.
        #if os(macOS)
            @State private var sharePresented = false
            @State private var shareItemURL: URL?
        #endif
    #endif


    let report: CrashReport

    public init(report: CrashReport) {
        self.report = report
    }

    private var manager: CrashReportManager {
        environments.crashReportManager
    }


        private func saveReport(includeConfig: Bool, includeLog: Bool, useAgeEncryption: Bool) async {
            do {
                let zipURL = try await createReportZip(
                    reportID: report.id, fileURL: report.fileURL,
                    cacheSubdirectory: ReportType.crash.directoryName, includeConfig: includeConfig, includeLog: includeLog,
                    encrypt: useAgeEncryption
                )
                exportDocument = HakoReportZipDocument(url: zipURL)
                showExporter = true
            } catch {
                alert = AlertState(action: "save crash report", error: error)
            }
        }

        private func shareReport(includeConfig: Bool, includeLog: Bool, useAgeEncryption: Bool) async {
            do {
                let zipURL = try await createReportZip(
                    reportID: report.id, fileURL: report.fileURL,
                    cacheSubdirectory: ReportType.crash.directoryName, includeConfig: includeConfig, includeLog: includeLog,
                    encrypt: useAgeEncryption
                )
                #if os(iOS)
                    presentShareSheet(zipURL)
                #elseif os(macOS)
                    shareItemURL = zipURL
                    sharePresented = true
                #endif
            } catch {
                alert = AlertState(action: "export crash reports", error: error)
            }
        }


    public var body: some View {
        // The report read views were a `FormView` plus a separate chrome call. The
        // report scaffold is the same page - the system grouped form and the shared
        // chrome - with the page canvas, the empty and loading conventions and one
        // place that decides all of it.
        HakoReportScaffold(title: report.date.formatted(date: .abbreviated, time: .shortened)) {
            if !isLoading, !files.isEmpty {
                Section("Files") {
                    ForEach(files) { file in
                        // Identified, because the read view is what distinguishes "the report
                        // opened" from "the tap did nothing", and a case can only ask for it in
                        // one language if it asks by the English header text.
                        if file.id == .metadata {
                            FormNavigationLink {
                                MetadataFormView(url: file.fileURL, title: file.displayName)
                            } label: {
                                Text(file.displayName)
                            }
                            .accessibilityIdentifier("hako.report.file")
                        } else {
                            FormNavigationLink {
                                HakoReportFileContentView(fileURL: file.fileURL, displayName: file.displayName)
                            } label: {
                                Text(file.displayName)
                            }
                            .accessibilityIdentifier("hako.report.file")
                        }
                    }
                }
            }
        }
        .overlay {
            if isLoading {
                ProgressView()
            } else if files.isEmpty {
                HakoEmptyState(
                    symbol: "doc.text",
                    title: "Empty",
                    message: "This report has no content."
                )
            }
        }
        .onAppear {
            Task {
                files = await manager.availableFiles(for: report)
                manager.markAsRead(report)
                isLoading = false
            }
        }
        .alert($alert)

            .fileExporter(
                isPresented: $showExporter,
                document: exportDocument,
                contentType: useAgeEncryption ? .data : .zip,
                defaultFilename: useAgeEncryption ? "\(report.id).zip.age" : "\(report.id).zip"
            ) { result in
                exportDocument = nil
                if case let .failure(error) = result {
                    alert = AlertState(action: "save crash report", error: error)
                }
            }
            // `#if !os(tvOS)`, as the original has it: `HakoReportShareAction` is declared under that
            // condition in `ApplicationLibrary/Views/Tools/ReportShared.swift:135`, and this sheet is the
            // only thing that reads the property holding one. Wrapping the modifier rather than the
            // property alone keeps every read of it inside the same condition, which is the pairing the
            // platform check looks for.
            #if !os(tvOS)
                .sheet(isPresented: $sharePopupPresented, onDismiss: {
                    let action = pendingAction
                    pendingAction = nil
                    switch action {
                    case .save:
                        Task { await saveReport(includeConfig: includeConfig, includeLog: includeLog, useAgeEncryption: useAgeEncryption) }
                    case .share:
                        Task { await shareReport(includeConfig: includeConfig, includeLog: includeLog, useAgeEncryption: useAgeEncryption) }
                    case .none:
                        break
                    }
                }) {
                    HakoReportSharePopup(
                        hasConfig: files.contains(where: { $0.id == .configContent }),
                        hasLog: false,
                        includeConfig: $includeConfig,
                        includeLog: $includeLog,
                        useAgeEncryption: $useAgeEncryption,
                        onSave: { pendingAction = .save },
                        onShare: { pendingAction = .share }
                    )
                }
            #endif
            #if os(macOS)
            .background(SharingServicePicker($sharePresented, $alert, $shareItemURL))
            #endif

        .toolbar {
            if !isLoading, !files.isEmpty {


                    Button {
                        includeConfig = false
                        includeLog = true
                        useAgeEncryption = false
                        sharePopupPresented = true
                    } label: {
                        Label("Share", systemImage: "square.and.arrow.up")
                    }
                    Button(role: .destructive) {
                        Task {
                            await manager.delete(report)
                            dismiss()
                        }
                    } label: {
                        Label("Delete", systemImage: "trash.fill")
                            .foregroundStyle(.red)
                    }
                    .tint(.red)

            }
        }
    }
}
