//
//  HakoEditProfileView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Profile/HakoEditProfileView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI

@MainActor
public struct HakoEditProfileView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var profile: Profile
    @StateObject private var viewModel = EditProfileViewModel()

    public init() {}

    public var body: some View {


            iOSBody

    }

    private var formContent: some View {
        FormView {
            Section {
                FormItem(String(localized: "Name")) {
                    TextField("Name", text: $profile.name, prompt: Text("Required"))
                        .multilineTextAlignment(.trailing)
                }
                Picker(selection: $profile.type) {
                    Text("Local").tag(ProfileType.local)
                    Text("iCloud").tag(ProfileType.icloud)
                    Text("Remote").tag(ProfileType.remote)
                } label: {
                    Text("Type")
                }
                .disabled(true)
                if profile.type == .icloud {
                    FormItem(String(localized: "Path")) {
                        TextField("Path", text: $profile.path, prompt: Text("Required"))
                            .multilineTextAlignment(.trailing)
                    }
                } else if profile.type == .remote {
                    FormItem(String(localized: "URL")) {
                        TextField("URL", text: $profile.remoteURL.unwrapped(""), prompt: Text("Required"))
                            .multilineTextAlignment(.trailing)

                            .keyboardType(.URL)

                    }
                    Toggle("Auto Update", isOn: $profile.autoUpdate)
                    FormItem(String(localized: "Auto Update Interval")) {
                        TextField("Auto Update Interval", text: $profile.autoUpdateInterval.stringBinding(defaultValue: 60), prompt: Text("In Minutes"))
                            .multilineTextAlignment(.trailing)

                            .keyboardType(.numberPad)

                    }
                }
            } footer: {
                if profile.type == .icloud {
                    let fileName = profile.path.isEmpty ? String(localized: "FileName") : profile.path
                    Text("File will be located at iCloud Drive/sing-box/\(fileName)")
                }
            }
            if profile.type == .remote {
                Section("Status") {
                    FormTextItem("Last Updated", profile.lastUpdated!.relativeFormat)
                }
            }


                HakoProfileActionToolbar(profile: profile, viewModel: viewModel)

        }
    }


        private var iOSBody: some View {
            formContent
                .onChangeCompat(of: profile.name) {
                    viewModel.markAsChanged()
                }
                .onChangeCompat(of: profile.remoteURL) {
                    viewModel.markAsChanged()
                }
                .onChangeCompat(of: profile.autoUpdate) {
                    viewModel.markAsChanged()
                }
                .disabled(viewModel.isLoading)

                .toolbar {
                    ToolbarItem(placement: .navigationBarTrailing) {
                        Button("Save") {
                            viewModel.isLoading = true
                            Task {
                                await viewModel.saveProfile(profile, environments: environments)
                            }
                        }
                        .disabled(!viewModel.isChanged)
                        // The same primary treatment the creation page's button uses, so the
                        // page's action looks the same before and after a configuration exists -
                        // the review's "the two states must not maintain two button layouts".
                        .hakoPrimaryActionButtonStyle()
                    }
                }

                .alert($viewModel.alert)
                .navigationTitle("Edit Profile")
        }

}
