//
//  HakoTailscaleExitNodePickerView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/HakoTailscaleExitNodePickerView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI

@MainActor
public struct HakoTailscaleExitNodePickerView: View {
    @ObservedObject var viewModel: TailscaleStatusViewModel
    let endpointTag: String

    @State private var searchText = ""
    @Environment(\.dismiss) private var dismiss

    public init(viewModel: TailscaleStatusViewModel, endpointTag: String) {
        self.viewModel = viewModel
        self.endpointTag = endpointTag
    }

    private var endpoint: TailscaleEndpointData? {
        viewModel.endpoint(tag: endpointTag)
    }

    private var candidates: [(group: TailscaleUserGroupData, peer: TailscalePeerData)] {
        guard let endpoint else { return [] }
        let selfStableID = endpoint.selfPeer?.stableID
        var rows: [(TailscaleUserGroupData, TailscalePeerData)] = []
        for group in endpoint.userGroups {
            for peer in group.peers where peer.exitNodeOption && peer.stableID != selfStableID {
                if searchText.isEmpty || peer.displayName.localizedCaseInsensitiveContains(searchText) || peer.hostName.localizedCaseInsensitiveContains(searchText) {
                    rows.append((group, peer))
                }
            }
        }
        return rows
    }

    public var body: some View {
        List {
            Button {
                select(stableID: "")
            } label: {
                HStack {
                    Text("Disabled")
                        .foregroundStyle(.foreground)
                    Spacer()
                    HakoSelectionMark(isSelected: endpoint?.exitNode == nil)
                }
                .contentShape(Rectangle())
            }


            ForEach(Array(candidates.enumerated()), id: \.offset) { _, row in
                Button {
                    select(stableID: row.peer.stableID)
                } label: {
                    HStack {
                        Image(systemName: "circle.fill")
                            .font(.system(size: 8))
                            .foregroundStyle(row.peer.online ? .green : Color(.systemGray))
                        VStack(alignment: .leading, spacing: 4) {
                            Text(row.peer.displayName)
                                .foregroundStyle(.foreground)
                                .lineLimit(1)
                            if let firstIP = row.peer.tailscaleIPs.first {
                                Text(firstIP)
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                        Spacer()
                        HakoSelectionMark(isSelected: endpoint?.exitNode?.stableID == row.peer.stableID)
                    }
                    .contentShape(Rectangle())
                }


            }
        }

        .searchable(text: $searchText, placement: .navigationBarDrawer(displayMode: .always))


        .navigationTitle("Exit Node")
    }

    private func select(stableID: String) {
        Task {
            await viewModel.setExitNode(endpointTag: endpointTag, stableID: stableID)
            dismiss()
        }
    }
}
