//
//  HakoQRSDisplayView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Profile/HakoQRSDisplayView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Foundation
import QRCode
import SwiftUI

@MainActor
public struct HakoQRSDisplayView: View {
    private static let recoveryFactor = 1.3

    @Environment(\.dismiss) private var dismiss
    @Environment(\.openURL) private var openURL
    private let data: Data
    private let filename: String?

    @State private var generator: QRSImageGenerator?
    @State private var fps: Double = 10
    @State private var sliceSize: Double = 500
    @State private var generationTask: Task<Void, Never>?


    public init(data: Data, filename: String? = nil) {
        self.data = data
        self.filename = filename
    }

    public var body: some View {
        VStack(spacing: 16) {
            TimelineView(.periodic(from: .now, by: 1.0 / fps)) { context in
                Group {
                    if let image = generator?.currentImage {
                        Image(decorative: image, scale: 1.0)
                            .resizable()
                            .interpolation(.none)
                            .aspectRatio(1, contentMode: .fit)
                    } else {
                        ProgressView()
                            .frame(width: 280, height: 280)
                    }
                }
                .onChange(of: context.date) { _ in
                    generator?.advanceFrame()
                }
            }

            VStack(spacing: 8) {
                HStack {
                    Text(String(localized: "FPS"))
                    Spacer()


                        Text(verbatim: "\(Int(fps))")
                            .foregroundStyle(.secondary)

                }


                    Slider(value: $fps, in: 1 ... 60, step: 1)


                HStack {
                    Text(String(localized: "Slice Size"))
                    Spacer()


                        Text(verbatim: "\(Int(sliceSize))")
                            .foregroundStyle(.secondary)

                }


                    Slider(value: $sliceSize, in: 100 ... 1500, step: 100)

            }
            .padding(.horizontal)

            HStack(spacing: 12) {
                Button {


                        openURL(URL(string: "https://github.com/qifi-dev/qrs")!)

                } label: {
                    HStack(spacing: 4) {
                        Image(systemName: "info.circle")
                        Text(String(localized: "What is QRS"))
                    }
                    .frame(maxWidth: .infinity)
                }
                .hakoSecondaryActionButtonStyle()

                Button {
                    dismiss()
                } label: {
                    HStack(spacing: 4) {
                        Image(systemName: "xmark")
                        Text(String(localized: "Close"))
                    }
                    .frame(maxWidth: .infinity)
                }
                .hakoPrimaryActionButtonStyle()
            }
            .padding(.horizontal)
        }


        .padding([.horizontal, .bottom])

        .onAppear {
            setupGenerator()
        }
        .onDisappear {
            generator?.cancel()
            generationTask?.cancel()
        }
        .onChange(of: sliceSize) { _ in
            setupGenerator()
        }


    }

    private func setupGenerator() {
        generator?.cancel()
        generationTask?.cancel()

        let newGenerator = QRSImageGenerator(
            foregroundColor: CGColor(gray: 0.0, alpha: 1.0),
            bufferSize: 30
        )
        generator = newGenerator

        generationTask = Task {
            let (encoder, requiredFrames) = await createEncoder()
            if Task.isCancelled {
                return
            }

            newGenerator.setExpectedFrames(requiredFrames)

            let fountain = encoder.fountain()
            for _ in 0 ..< requiredFrames {
                if Task.isCancelled {
                    return
                }
                guard let block = fountain.next() else { continue }
                await newGenerator.addFrame(block)
            }
        }
    }

    private nonisolated func createEncoder() async -> (LubyTransformEncoder, Int) {
        await Task.detached(priority: .userInitiated) { [data, filename, sliceSize] in
            let wrappedData = BinaryMeta.appendFileHeaderMeta(
                data: data,
                filename: filename,
                contentType: "application/octet-stream"
            )
            let sliceSizeInt = Int(sliceSize)
            let encoder = LubyTransformEncoder(data: wrappedData, sliceSize: sliceSizeInt, compress: true)
            let requiredFrames = Self.calculateRequiredFrames(dataSize: wrappedData.count, sliceSize: sliceSizeInt)
            return (encoder, requiredFrames)
        }.value
    }

    private nonisolated static func calculateRequiredFrames(dataSize: Int, sliceSize: Int) -> Int {
        let k = (dataSize + sliceSize - 1) / sliceSize
        if k == 0 {
            return 1
        }
        return max(Int(Double(k) * recoveryFactor), k + 5)
    }
}

@MainActor
public struct HakoQRSSheet: View {
    private let profileName: String
    private let profileData: Data

    public init(profileName: String, profileData: Data) {
        self.profileName = profileName
        self.profileData = profileData
    }

    public var body: some View {


            HakoQRSDisplayView(data: profileData, filename: "\(profileName).bpf")
                .modifier(LargeSheetModifier())

    }
}


    private struct LargeSheetModifier: ViewModifier {
        func body(content: Content) -> some View {
            if #available(iOS 16.0, tvOS 17.0, *) {
                content
                    .presentationDetents([.large])
                    .presentationDragIndicator(.visible)
            } else {
                content
            }
        }
    }

