//
//  HakoPowerReportListView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/HakoPowerReportListView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

@MainActor
public struct HakoPowerReportListView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @State private var isLoading = true
    @State private var powerReportEnabled = false
    @State private var alert: AlertState?


    public init() {}

    private var manager: PowerReportManager {
        environments.powerReportManager
    }

    public var body: some View {
        HakoReportScaffold(title: String(localized: "Power Report")) {
            if !isLoading {
                HakoSettingsSection(
                    footnote: "Record a report for each service run."
                ) {
                    HakoToggleRow(
                        String(localized: "Enable Power Report"),
                        isOn: $powerReportEnabled
                    ) { newValue in
                        Task {
                            await SharedPreferences.powerReportEnabled.set(newValue)
                            await restartService()
                        }
                    }
                }

                HakoSettingsSection("Reports", footnote: "A report is saved for each service run.") {
                    if manager.reports.isEmpty {
                        HakoCardEmptyState(
                            symbol: "battery.50percent",
                            title: "No power reports",
                            message: "A report is recorded for each service run."
                        )
                        .frame(minHeight: 180)
                    } else {
                        ForEach(manager.reports) { report in


                                FormNavigationLink {
                                    HakoPowerReportDetailView(report: report)
                                } label: {
                                    reportLabel(report)
                                }
                                // The report's own identifier, as the crash list's rows have:
                                // a test can address the row rather than guess at it by position.
                                .accessibilityIdentifier("hako.report.\(report.id)")

                        }
                    }
                }
            }
        }
        .overlay {
            if isLoading {
                ProgressView()
            }
        }
        .onAppear {
            Task {
                await manager.refresh()
                powerReportEnabled = await SharedPreferences.powerReportEnabled.get()
                isLoading = false
            }
        }
        .alert($alert)


            .toolbar {


                    ToolbarItem {
                        PowerReportToolbarMenu(manager: manager)
                    }

            }
    }

    private func reportLabel(_ report: PowerReport) -> some View {


            HakoNavigationRow(
                title: report.date.formatted(date: .abbreviated, time: .shortened),
                subtitle: report.origin == ReportArchive.tvOSDeviceOrigin
                    ? String(localized: "From Apple TV")
                    : String(localized: "From this device"),
                systemImage: "battery.50percent",
                tint: HakoAccentRole.neutral.color,
                badge: report.isRead ? nil : String(localized: "Unread"),
                badgeEmphasis: .info
            )

    }

    private func restartService() async {
        guard let profile = environments.extensionProfile, profile.status.isConnected else {
            return
        }
        do {
            try await profile.restart()
        } catch {
            alert = AlertState(action: "restart service", error: error)
        }
    }
}


    private struct PowerReportToolbarMenu: View {
        @ObservedObject var manager: PowerReportManager

        var body: some View {
            if !manager.reports.isEmpty {
                Menu {
                    Button(role: .destructive) {
                        Task {
                            await manager.deleteAll()
                        }
                    } label: {
                        Label("Delete All", systemImage: "trash.fill")
                    }
                } label: {
                    Label("Others", systemImage: "line.3.horizontal.circle")
                }
            }
        }
    }

