//
//  HakoTerminalSessionContentView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Terminal/HakoTerminalSessionContentView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//


#if canImport(GhosttyTerminal)
    import GhosttyTerminal
#endif
    import Library
    import SwiftUI

    @MainActor
    struct HakoTerminalSessionContentView: View {
        @ObservedObject var viewModel: TerminalWrapperViewModel
        let presentedSession: TailscaleSSHPresentedSession
        var isActive: Bool = true
        var onCloseSession: (() -> Void)?
        @Environment(\.dismiss) private var dismiss

        var body: some View {
            ZStack {

                    Color(uiColor: .systemBackground)
                        .ignoresSafeArea()


                TailsshTerminalSurfaceView(
                    state: viewModel.terminalState,
                    extras: viewModel.extras,
                    isActive: isActive
                )
                if case .connecting = viewModel.phase {
                    VStack(spacing: 16) {
                        ProgressView()
                            .controlSize(.large)
                        if let banner = viewModel.authBanner, !banner.isEmpty {
                            Text(Self.bannerAttributedString(banner))
                                .font(.callout)
                                .multilineTextAlignment(.leading)
                                .foregroundColor(.primary)
                                .padding()
                                .background(HakoProductPalette.system.control, in: RoundedRectangle(cornerRadius: HakoTheme.Radius.control, style: .continuous))
                                .padding(.horizontal)
                                .frame(maxWidth: 480)
                                .textSelection(.enabled)
                        }
                    }
                } else if case let .finished(reason) = viewModel.phase {
                    VStack {
                        Spacer()
                        if let banner = viewModel.authBanner, !banner.isEmpty {
                            Text(Self.bannerAttributedString(banner))
                                .font(.callout)
                                .multilineTextAlignment(.leading)
                                .foregroundColor(.primary)
                                .padding()
                                .background(HakoProductPalette.system.control, in: RoundedRectangle(cornerRadius: HakoTheme.Radius.control, style: .continuous))
                                .padding(.horizontal)
                                .frame(maxWidth: 480)
                                .textSelection(.enabled)
                        }
                        HStack(spacing: 12) {
                            Text(reason.displayText)
                                .font(.callout)
                                .multilineTextAlignment(.leading)
                                .textSelection(.enabled)
                            Spacer(minLength: 8)
                            Button("Close") {
                                if let onCloseSession {
                                    onCloseSession()
                                } else {
                                    dismiss()
                                }
                            }
                            .hakoPrimaryActionButtonStyle()
                        }
                        .padding()
                        .background(HakoProductPalette.system.card, in: RoundedRectangle(cornerRadius: HakoTheme.Radius.card, style: .continuous))
                        .padding()
                    }
                }
            }
        }

        var displayedTitle: String {
            Self.displayTitle(
                phase: viewModel.phase,
                extrasTitle: viewModel.extras.title,
                peerHostName: presentedSession.peerHostName
            )
        }

        static func displayTitle(
            phase: TerminalWrapperViewModel.Phase,
            extrasTitle: String,
            peerHostName: String
        ) -> String {
            if case .connecting = phase {
                return peerHostName
            }
            let remote = extrasTitle.trimmingCharacters(in: .whitespaces)
            return remote.isEmpty ? peerHostName : remote
        }

        static func bannerAttributedString(_ text: String) -> AttributedString {
            var attributed = AttributedString(text)
            guard let detector = try? NSDataDetector(types: NSTextCheckingResult.CheckingType.link.rawValue) else {
                return attributed
            }
            let nsText = text as NSString
            let matches = detector.matches(in: text, range: NSRange(location: 0, length: nsText.length))
            for match in matches {
                guard let url = match.url,
                      let range = Range(match.range, in: attributed) else { continue }
                attributed[range].link = url
                attributed[range].foregroundColor = .accentColor
                attributed[range].underlineStyle = .single
            }
            return attributed
        }
    }

