//
//  HakoNewProfileMenuView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Profile/HakoNewProfileMenuView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Foundation
import Libbox
import Library
import SwiftUI
import UniformTypeIdentifiers

@MainActor
public struct HakoNewProfileMenuView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @Environment(\.dismiss) private var dismiss
    @State private var alert: AlertState?
    @State private var importRequest: HakoNewProfileView.ImportRequest?
    @State private var localImportRequest: HakoNewProfileView.LocalImportRequest?
    @State private var manualCreateSucceeded = false

        @State private var showFileImporter = false
        @State private var showQRScanner = false

    /// The manual-creation push, on the touch client.
    @State private var showManualCreate = false


    private var onComplete: (() -> Void)?

    public init(onComplete: (() -> Void)? = nil) {
        self.onComplete = onComplete
    }

    public var body: some View {


            otherBody

    }


    private var otherBody: some View {
        HakoModalScaffold(title: String(localized: "Add Configuration")) {
            Group {
                if let request = importRequest {
                    HakoNewProfileView(request, onSuccess: { profile in
                        await SharedPreferences.selectedProfileID.set(profile.mustID)
                        complete()
                    })
                    .environmentObject(environments)
                } else if let request = localImportRequest {
                    HakoNewProfileView(localImportRequest: request, onSuccess: { profile in
                        await SharedPreferences.selectedProfileID.set(profile.mustID)
                        complete()
                    })
                    .environmentObject(environments)
                } else {
                    menuContent
                }
            }
            .onChangeCompat(of: manualCreateSucceeded) { newValue in
                if newValue {
                    complete()
                }
            }
            .alert($alert)

                .fileImporter(
                    isPresented: $showFileImporter,
                    allowedContentTypes: [.profile, .json],
                    allowsMultipleSelection: false
                ) { result in
                    handleFileImport(result)
                }
                .sheet(isPresented: $showQRScanner) {
                    QRScannerView { result in
                        handleQRScanResult(result)
                    }
                }

        }
        // Outside the scaffold, not inside its content.
        //
        // `HakoModalScaffold` wraps its content in a `Form`, so a hidden `NavigationLink`
        // attached to that content is a *row* - and the platform gives a row that navigates a
        // disclosure indicator, which is where the stray chevron at the trailing edge of the
        // tile row came from. Attaching it to the scaffold's own result is what puts it outside
        // the form. Two earlier attempts missed this by attaching it to the content and
        // assuming "inside the modal" and "outside the form" were the same thing.
        .background {

                NavigationDestinationCompat(isPresented: $showManualCreate) {
                    // Capturing anything that holds the sheet's DismissAction here makes
                    // SwiftUI on iOS 17 loop forever laying the pushed view out.
                    HakoNewProfileView(onSuccess: { [$manualCreateSucceeded] profile in
                        await SharedPreferences.selectedProfileID.set(profile.mustID)
                        $manualCreateSucceeded.wrappedValue = true
                    })
                    .environmentObject(environments)
                    // The push supplies the chrome, as every other pushed page's presenter
                    // does. Without it the editor wore the platform's own back control and the
                    // platform's title.
                    .hakoNavigationChrome(title: String(localized: "New Configuration"))
                }

        }
    }

    private func complete() {
        if let onComplete {
            onComplete()
        } else {
            dismiss()
        }
    }

    /// How a configuration gets in.
    ///
    /// The three ways in are the page's whole content, so they are tiles rather than rows:
    /// a row would say "Import from File" in the same voice as every setting on every other
    /// page, and this is not a setting - it is the choice the sheet exists to offer. The
    /// focus platform keeps its rows, whose larger type suits a television.
    @ViewBuilder
    private var menuContent: some View {


            HakoSettingsSection {
                HStack(alignment: .top, spacing: HakoTheme.Spacing.standard) {
                    HakoActionTile(
                        String(localized: "Import from File"),
                        systemImage: "doc.badge.plus",
                        tint: HakoAccentRole.neutral
                    ) {
                        showFileImporter = true
                    }

                    HakoActionTile(
                        String(localized: "Scan QR Code"),
                        systemImage: "qrcode.viewfinder",
                        tint: HakoAccentRole.neutral
                    ) {
                        showQRScanner = true
                    }


                        // A button, not a `NavigationLink`. A link inside a form is a row, and
                        // the platform gives a row that navigates a disclosure indicator - which
                        // on a row of three action tiles lands at the card's trailing edge, where
                        // it reads as belonging to the card rather than to the third tile. The
                        // tile is its own affordance, named and illustrated, and the reference's
                        // tiles carry no chevron at all. The push is the same hidden destination
                        // the rest of this client uses.
                        HakoActionTile(
                            String(localized: "Create Manually"),
                            systemImage: "square.and.pencil",
                            tint: HakoAccentRole.neutral
                        ) {
                            showManualCreate = true
                        }
                        .accessibilityIdentifier("hako.profile.createManually")

                }
            }

    }


        private func handleFileImport(_ result: Result<[URL], Error>) {
            Task { @MainActor in
                do {
                    let urls = try result.get()
                    guard let url = urls.first else { return }

                    if url.pathExtension.lowercased() == "json" {
                        let fileName = url.deletingPathExtension().lastPathComponent
                        localImportRequest = HakoNewProfileView.LocalImportRequest(name: fileName, fileURL: url)
                        return
                    }

                    let data = try await BlockingIO.run {
                        try url.withRequiredSecurityScopedAccess(
                            or: NSError(domain: "HakoNewProfileMenuView", code: 0, userInfo: [NSLocalizedDescriptionKey: String(localized: "Missing access to selected file")])
                        ) {
                            try Data(contentsOf: url)
                        }
                    }
                    let content = try LibboxProfileContent.from(data)

                    alert = AlertState(
                        title: String(localized: "Import Profile"),
                        message: String(localized: "Are you sure to import profile \(content.name)?"),
                        primaryButton: .default(String(localized: "Import")) {
                            Task {
                                do {
                                    try await content.importProfile()
                                    environments.profileUpdate.send()
                                    complete()
                                } catch {
                                    alert = AlertState(action: "import profile", error: error)
                                }
                            }
                        },
                        secondaryButton: .cancel()
                    )
                } catch {
                    alert = AlertState(action: "read imported profile file", error: error)
                }
            }
        }


        private func handleQRScanResult(_ result: QRScanResult) {
            switch result {
            case let .qrCode(string, _):
                handleQRCodeString(string)
            case let .qrsData(data):
                handleQRSData(data)
            }
        }

        private func handleQRCodeString(_ string: String) {
            var error: NSError?
            let remoteProfile = LibboxParseRemoteProfileImportLink(string, &error)
            if let error {
                alert = AlertState(action: "parse QR code profile link", error: error)
                return
            }
            guard let remoteProfile else {
                alert = AlertState(errorMessage: String(localized: "The QR code does not contain a valid profile import link."))
                return
            }
            importRequest = HakoNewProfileView.ImportRequest(name: remoteProfile.name, url: remoteProfile.url)
        }

        private func handleQRSData(_ data: Data) {
            do {
                let (actualData, _, _) = try BinaryMeta.readFileHeaderMeta(buffer: data)
                let content = try LibboxProfileContent.from(actualData)
                alert = AlertState(
                    title: String(localized: "Import Profile"),
                    message: String(localized: "Are you sure to import profile \(content.name)?"),
                    primaryButton: .default(String(localized: "Import")) {
                        Task {
                            do {
                                try await BlockingIO.run {
                                    var error: NSError?
                                    LibboxCheckConfig(content.config, &error)
                                    if let error {
                                        throw error
                                    }
                                }
                                try await content.importProfile()
                                environments.profileUpdate.send()
                                complete()
                            } catch {
                                alert = AlertState(action: "import profile", error: error)
                            }
                        }
                    },
                    secondaryButton: .cancel()
                )
            } catch {
                alert = AlertState(action: "decode QRS profile data", error: error)
            }
        }

}
