//
//  HakoGroupItemView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Groups/HakoGroupItemView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

@MainActor
public struct HakoGroupItemView: View {
    @EnvironmentObject private var listViewModel: GroupListViewModel

    private let groupTag: String
    private let selectable: Bool
    private let isSelected: Bool
    private let item: OutboundGroupItem

    public init(groupTag: String, selectable: Bool, isSelected: Bool, item: OutboundGroupItem) {
        self.groupTag = groupTag
        self.selectable = selectable
        self.isSelected = isSelected
        self.item = item
    }

    public var body: some View {
        Button {
            if selectable, !isSelected {
                listViewModel.selectOutbound(groupTag: groupTag, outboundTag: item.tag)
            }
        } label: {
            VStack(alignment: .leading, spacing: HakoTheme.Spacing.tight) {
                HStack(spacing: HakoTheme.Spacing.compact) {
                    Text(item.tag)
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(.foreground)
                        .lineLimit(1)
                        .truncationMode(.tail)


                }
                HStack {
                    Text(item.displayType)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    Spacer(minLength: 8)
                    if item.urlTestDelay > 0 {
                        Text(item.delayString)
                            .font(.caption.monospacedDigit().weight(.semibold))
                            .foregroundColor(item.delayColor)
                    }
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)

                .padding(EdgeInsets(
                top: HakoTheme.Spacing.cardGap,
                leading: HakoTheme.Spacing.row,
                bottom: HakoTheme.Spacing.cardGap,
                trailing: HakoTheme.Spacing.row
            ))
                .contentShape(Rectangle())

        }

        .hakoCircularIconButtonStyle()
        .background(
            RoundedRectangle(cornerRadius: HakoTheme.Radius.control, style: .continuous)
                .fill(isSelected ? AnyShapeStyle(Color.accentColor.opacity(0.12)) : AnyShapeStyle(itemBackground))
        )
        .overlay(
            RoundedRectangle(cornerRadius: HakoTheme.Radius.control, style: .continuous)
                .strokeBorder(isSelected ? Color.accentColor : Color.urlTestNeutral, lineWidth: 1)
        )
        .animation(.easeOut(duration: 0.12), value: isSelected)
        .contextMenu {
            Button {
                listViewModel.performURLTest(item.tag)
            } label: {
                Label("URLTest", systemImage: "bolt.fill")
            }
        }

    }

    private var itemBackground: Color {

            return Color(uiColor: .systemGroupedBackground)


    }
}
