//
//  HakoReportShared.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/ReportShared.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI
import UniformTypeIdentifiers


#if canImport(UIKit)
    import UIKit
#endif


struct HakoReportLabel: View {
    let date: Date
    let isRead: Bool
    let origin: String?

    var body: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(isRead ? .clear : .blue)
                .frame(width: 10, height: 10)
            VStack(alignment: .leading, spacing: 2) {
                Text(date, format: .dateTime)
                    .fontWeight(isRead ? .regular : .semibold)
                HStack(spacing: 4) {
                    Image(systemName: origin == ReportArchive.tvOSDeviceOrigin ? "appletv.fill" : Self.localDeviceIcon)
                    Text(origin == ReportArchive.tvOSDeviceOrigin ? "Apple TV" : "Local")
                }
                .font(.caption)
                .foregroundStyle(.secondary)
            }
        }
    }


        private static let localDeviceIcon = "iphone"


}

@MainActor
struct HakoReportFileContentView: View {
    @State private var content = ""
    @State private var isLoading = true

    let fileURL: URL
    let displayName: String

    var body: some View {
        Group {
            if isLoading {
                ProgressView()
                    .onAppear {
                        Task {
                            content = await Self.loadContent(fileURL: fileURL)
                            isLoading = false
                        }
                    }
            } else if content.isEmpty {
                HakoEmptyState(
                    symbol: "doc.text",
                    title: "Empty",
                    message: "This report has no content."
                )
            } else {
                PlainTextView(content: content)
            }
        }
        .hakoNavigationChrome(title: displayName)
    }

    private static let maxContentBytes: UInt64 = 2 * 1024 * 1024

    private nonisolated static func loadContent(fileURL: URL) async -> String {
        await BlockingIO.run {
            guard let handle = try? FileHandle(forReadingFrom: fileURL) else {
                return ""
            }
            defer { try? handle.close() }
            let size = (try? handle.seekToEnd()) ?? 0
            var truncated = false
            if size > maxContentBytes {
                truncated = true
                try? handle.seek(toOffset: size - maxContentBytes)
            } else {
                try? handle.seek(toOffset: 0)
            }
            guard let data = try? handle.readToEnd(), var content = String(data: data, encoding: .utf8) else {
                return ""
            }
            if truncated {
                if let lineStart = content.firstIndex(of: "\n") {
                    content = String(content[content.index(after: lineStart)...])
                }
                content = "…\n" + content
            }
            return content
        }
    }
}


// `createReportZip(reportID:fileURL:cacheSubdirectory:includeConfig:includeLog:encrypt:)` is deliberately
// **not** copied here. It is a module-scope free function, so renaming the file's *types* into the Hako
// namespace did nothing to it, and upstream's `Tools/ReportShared.swift:108` declares the same signature
// under the same live condition (`#if !os(tvOS)`), in the same target:
//
//     error: invalid redeclaration of 'createReportZip(reportID:fileURL:cacheSubdirectory:includeConfig:includeLog:encrypt:)'
//
// The three ported detail pages spell the bare name, which is what they should call - the zip has no
// presentation in it. A copy here would be dead as well as duplicate.


    enum HakoReportShareAction {
        case save
        case share
    }

    @MainActor
    struct HakoReportSharePopup: View {
        @Environment(\.dismiss) private var dismiss

        let hasConfig: Bool
        let hasLog: Bool
        @Binding var includeConfig: Bool
        @Binding var includeLog: Bool
        @Binding var useAgeEncryption: Bool
        let onSave: () -> Void
        let onShare: () -> Void

        var body: some View {
            NavigationSheet(title: "Share", size: .medium) {
                FormView {
                    if hasConfig || hasLog {
                        Section {
                            if hasLog {
                                Toggle("With Log", isOn: $includeLog)
                            }
                            if hasConfig {
                                Toggle("With Configuration", isOn: $includeConfig)
                            }
                        } footer: {
                            if hasLog {
                                Text("Logs and configuration files may contain private content and should not be made public.")
                            } else {
                                Text("Configuration files may contain private content and should not be made public.")
                            }
                        }
                    }
                    Section {
                        Toggle("Encrypt with age for Project S", isOn: $useAgeEncryption)
                    } footer: {
                        Text("[age](https://github.com/filosottile/age) is a modern and secure asymmetric encryption tool. When enabled, the zip file is encrypted with this project's public key so it can be posted publicly, e.g. in GitHub issues.")
                    }
                    Section {
                        FormButton {
                            onSave()
                            dismiss()
                        } label: {
                            Label("Save", systemImage: "square.and.arrow.down")
                        }
                        FormButton {
                            onShare()
                            dismiss()
                        } label: {
                            Label("Share", systemImage: "square.and.arrow.up")
                        }
                        .keyboardShortcut(.defaultAction)
                    }
                }
                .hakoModalClose()
            }
        }
    }

    struct HakoReportZipDocument: FileDocument {
        static var readableContentTypes: [UTType] {
            [.zip, .data]
        }

        private let url: URL

        init(url: URL) {
            self.url = url
        }

        init(configuration: ReadConfiguration) throws {
            guard let data = configuration.file.regularFileContents else {
                throw CocoaError(.fileReadCorruptFile)
            }
            let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
            try data.write(to: tempURL)
            url = tempURL
        }

        func fileWrapper(configuration _: WriteConfiguration) throws -> FileWrapper {
            try FileWrapper(url: url)
        }
    }


// `presentShareSheet(_:)` is deliberately **not** copied here either, for the same reason as
// `createReportZip`: it is a module-scope free function that the rename could not touch, and upstream's
// `Tools/ReportShared.swift:235` declares it under `#if os(iOS)` in this same target. Two declarations of
// one signature in one module do not build. The ported detail pages call the bare name, which reaches
// upstream's declaration - and `HakoReportSharePopup` below presents its own sheet through SwiftUI, so
// nothing in the Hako namespace needed a copy of the UIKit one.

