//
//  HakoGroupView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Groups/GroupView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

enum HakoGroupsLayout {


        static let dotSize: CGFloat = 11
        static let dotSpacing: CGFloat = 4
        static let dotCornerRadius: CGFloat = 4
        static let selectedDotSize: CGFloat = 4
        static let itemMinWidth: CGFloat = 170

}

@MainActor
public struct HakoGroupHeaderView: View {
    @EnvironmentObject private var listViewModel: GroupListViewModel

    private let group: OutboundGroup

    public init(group: OutboundGroup) {
        self.group = group
    }

    private var isTesting: Bool {
        listViewModel.testingGroups.contains(group.tag)
    }

    public var body: some View {
        HStack(spacing: HakoTheme.Spacing.compact) {
            Text(group.tag)
                .font(.headline)
                .lineLimit(1)
                .truncationMode(.tail)
            Text(group.displayType)
                .font(.subheadline)
                .foregroundStyle(.secondary)
                .lineLimit(1)
            Spacer(minLength: HakoTheme.Spacing.compact)
            HakoStatusBadge(String(group.items.count))
            HStack(spacing: 16) {
                Button {
                    listViewModel.performGroupURLTest(group.tag)
                } label: {
                    Group {
                        if isTesting {
                            ProgressView()
                                .controlSize(.small)
                        } else {
                            Image(systemName: "bolt.fill")
                        }
                    }
                    .frame(minWidth: 28, minHeight: 28)
                    .contentShape(Rectangle())
                }
                .disabled(isTesting)


                    .hakoCircularIconButtonStyle()

                Button {
                    listViewModel.toggleExpand(groupTag: group.tag)
                } label: {
                    Image(systemName: group.isExpand ? "chevron.up" : "chevron.down")
                        .frame(minWidth: 28, minHeight: 28)
                        .contentShape(Rectangle())
                }


                .hakoCircularIconButtonStyle()

            }
        }
        .padding(EdgeInsets(
            top: HakoTheme.Spacing.row,
            leading: HakoTheme.Spacing.standard,
            bottom: HakoTheme.Spacing.cardGap,
            trailing: HakoTheme.Spacing.compact
        ))
        .frame(maxWidth: .infinity, alignment: .leading)

            .contentShape(Rectangle())
            .onTapGesture {
                listViewModel.toggleExpand(groupTag: group.tag)
            }

            .cardSegment(top: true, bottom: false)
    }
}

@MainActor
public struct HakoGroupContentView: View {
    @EnvironmentObject private var listViewModel: GroupListViewModel

    private let group: OutboundGroup

    @State private var contentWidth: CGFloat = 0

    public init(group: OutboundGroup) {
        self.group = group
    }

    public var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            if group.isExpand {
                LazyVGrid(columns: [GridItem(.adaptive(minimum: HakoGroupsLayout.itemMinWidth), spacing: 10)], spacing: 10) {
                    ForEach(group.items, id: \.tag) { item in
                        HakoGroupItemView(
                            groupTag: group.tag,
                            selectable: group.selectable,
                            isSelected: group.selected == item.tag,
                            item: item
                        )
                    }
                }
            } else {
                dotGrid

                .contentShape(Rectangle())
                .onTapGesture {
                    listViewModel.toggleExpand(groupTag: group.tag)
                }

            }
        }
        .padding(EdgeInsets(top: 2, leading: 16, bottom: 14, trailing: 16))
        .frame(maxWidth: .infinity, alignment: .leading)
        .cardSegment(top: false, bottom: true)
    }

    private var dotGrid: some View {
        let columns = max(1, Int((contentWidth + HakoGroupsLayout.dotSpacing) / (HakoGroupsLayout.dotSize + HakoGroupsLayout.dotSpacing)))
        let horizontalSpacing: CGFloat
        if columns > 1 {
            horizontalSpacing = ((contentWidth - CGFloat(columns) * HakoGroupsLayout.dotSize) / CGFloat(columns - 1)).rounded(.down)
        } else {
            horizontalSpacing = 0
        }
        let rows = (group.items.count + columns - 1) / columns
        let height = CGFloat(rows) * HakoGroupsLayout.dotSize + CGFloat(max(0, rows - 1)) * HakoGroupsLayout.dotSpacing
        return Canvas { context, _ in
            for (index, item) in group.items.enumerated() {
                let x = CGFloat(index % columns) * (HakoGroupsLayout.dotSize + horizontalSpacing)
                let y = CGFloat(index / columns) * (HakoGroupsLayout.dotSize + HakoGroupsLayout.dotSpacing)
                let rect = CGRect(x: x, y: y, width: HakoGroupsLayout.dotSize, height: HakoGroupsLayout.dotSize)
                context.fill(
                    Path(roundedRect: rect, cornerRadius: HakoGroupsLayout.dotCornerRadius),
                    with: .color(item.delayColor)
                )
                if item.tag == group.selected {
                    let inset = (HakoGroupsLayout.dotSize - HakoGroupsLayout.selectedDotSize) / 2
                    context.fill(
                        Path(ellipseIn: rect.insetBy(dx: inset, dy: inset)),
                        with: .color(.white)
                    )
                }
            }
        }
        .frame(height: contentWidth > 0 ? height : 0)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background {
            GeometryReader { geometry in
                Color.clear
                    .onAppear {
                        contentWidth = geometry.size.width
                    }
                    .onChangeCompat(of: geometry.size.width) { newValue in
                        contentWidth = newValue
                    }
            }
        }
    }
}

struct HakoCardSegmentShape: Shape {
    let topRadius: CGFloat
    let bottomRadius: CGFloat

    func path(in rect: CGRect) -> Path {
        var path = Path()
        path.move(to: CGPoint(x: rect.minX, y: rect.minY + topRadius))
        path.addArc(
            center: CGPoint(x: rect.minX + topRadius, y: rect.minY + topRadius),
            radius: topRadius,
            startAngle: .degrees(180),
            endAngle: .degrees(270),
            clockwise: false
        )
        path.addLine(to: CGPoint(x: rect.maxX - topRadius, y: rect.minY))
        path.addArc(
            center: CGPoint(x: rect.maxX - topRadius, y: rect.minY + topRadius),
            radius: topRadius,
            startAngle: .degrees(270),
            endAngle: .degrees(0),
            clockwise: false
        )
        path.addLine(to: CGPoint(x: rect.maxX, y: rect.maxY - bottomRadius))
        path.addArc(
            center: CGPoint(x: rect.maxX - bottomRadius, y: rect.maxY - bottomRadius),
            radius: bottomRadius,
            startAngle: .degrees(0),
            endAngle: .degrees(90),
            clockwise: false
        )
        path.addLine(to: CGPoint(x: rect.minX + bottomRadius, y: rect.maxY))
        path.addArc(
            center: CGPoint(x: rect.minX + bottomRadius, y: rect.maxY - bottomRadius),
            radius: bottomRadius,
            startAngle: .degrees(90),
            endAngle: .degrees(180),
            clockwise: false
        )
        path.closeSubpath()
        return path
    }
}

extension View {
    func hakoCardSegment(top: Bool, bottom: Bool) -> some View {
        modifier(CardSegmentModifier(
            shape: HakoCardSegmentShape(
                topRadius: top ? HakoTheme.Radius.card : 0,
                bottomRadius: bottom ? HakoTheme.Radius.card : 0
            )
        ))
    }
}

private struct CardSegmentModifier: ViewModifier {
    let shape: HakoCardSegmentShape
    @Environment(\.colorScheme) private var colorScheme

    func body(content: Content) -> some View {
        content
            .background(backgroundColor)
            .clipShape(shape)
    }

    private var backgroundColor: Color {

            return HakoProductPalette.system.card


    }
}
