//
//  HakoProfileOverrideView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Setting/ProfileOverrideView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

public struct HakoProfileOverrideView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @State private var isLoading = true
    @State private var alert: AlertState?
    @State private var excludeDefaultRoute = false
    @State private var autoRouteUseSubRangesByDefault = false
    @State private var excludeAPNsRoute = false

    public init() {}

    /// The page the manual names as the second golden sample: related options in one
    /// card, one footnote per card, and the destructive action on its own at the end.
    ///
    /// The rows keep the same preferences with the same polarity. What changed is that
    /// the footnotes no longer read as configuration file text: "Append `0.0.0.0/31` and
    /// `::/127` to `route_exclude_address` if not exists." is a description of an
    /// implementation, and the user's question is what the switch does to their traffic.
    public var body: some View {
        HakoSettingsScaffold(title: String(localized: "Profile Override")) {
            if isLoading {
                HakoLoadingState()
                    .onAppear {
                        Task {
                            await loadSettings()
                        }
                    }
            } else {
                routingSections
                resetSection
            }
        }
        .alert($alert)
    }

    /// One section per setting, as the reference does it; see `PacketTunnelView`.
    private func settingSection(
        _ title: String,
        explanation: LocalizedStringKey,
        isOn: Binding<Bool>,
        set: @escaping (Bool) async -> Void
    ) -> some View {
        HakoSettingsSection(title, footnote: explanation) {
            HakoToggleRow(
                title,
                isOn: isOn
            ) { newValue in
                Task {
                    await set(newValue)
                    await reloadService()
                }
            }
        }
    }

    private var routingSections: some View {
        Group {
            settingSection(
                String(localized: "Hide VPN Icon"),
                explanation: "Stop the system from showing its VPN badge, by excluding the addresses the badge probes.",
                isOn: $excludeDefaultRoute
            ) { await SharedPreferences.excludeDefaultRoute.set($0) }

            settingSection(
                String(localized: "No Default Route"),
                explanation: "Route by subnet rather than taking over the default route. Fixes some HomeKit problems; on the Mac it stops Internet Sharing from working.",
                isOn: $autoRouteUseSubRangesByDefault
            ) { await SharedPreferences.autoRouteUseSubRangesByDefault.set($0) }

            settingSection(
                String(localized: "Exclude APNs Route"),
                explanation: "Keep Apple Push Notification traffic off the tunnel by bypassing its hosts.",
                isOn: $excludeAPNsRoute
            ) { await SharedPreferences.excludeAPNsRoute.set($0) }
        }
    }

    private var resetSection: some View {
        // The page's own footnote, under the reset card rather than above it: the review's item
        // is that it read as the caption of the three switches it sat beneath, when it is about
        // the page - changing any of them, including the reset, reloads the service.
        HakoSettingsSection(footnote: "Changing any of these reloads the running service.") {
            HakoDestructiveRow(
                String(localized: "Reset Profile Override"),
                subtitle: String(localized: "Use the defaults the client ships with."),
                systemImage: "eraser.fill"
            ) {
                Task {
                    await SharedPreferences.resetProfileOverride()
                    await reloadService()
                    isLoading = true
                }
            }
        }
    }

    private func reloadService() async {
        guard let profile = environments.extensionProfile, profile.status.isConnected else {
            return
        }
        do {
            try await profile.reloadService()
        } catch {
            alert = AlertState(action: "reload service", error: error)
        }
    }

    @MainActor
    private func loadSettings() async {
        excludeDefaultRoute = await SharedPreferences.excludeDefaultRoute.get()
        autoRouteUseSubRangesByDefault = await SharedPreferences.autoRouteUseSubRangesByDefault.get()
        excludeAPNsRoute = await SharedPreferences.excludeAPNsRoute.get()
        isLoading = false
    }
}
