//
//  HakoCrashReportListView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/CrashReportListView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI

@MainActor
public struct HakoCrashReportListView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @State private var isLoading = true
    @State private var alert: AlertState?


    public init() {}

    private var manager: CrashReportManager {
        environments.crashReportManager
    }

    public var body: some View {
        HakoReportScaffold(title: String(localized: "Crash Report")) {
            if !isLoading {
                HakoSettingsSection(
                    "Reports",
                    // The footnote explains the empty page. Under a list that has a report in
                    // it, it says the opposite of what the reader can see.
                    footnote: manager.reports.isEmpty
                        ? "You will receive a report when a crash occurs."
                        : nil
                ) {
                    if manager.reports.isEmpty {
                        HakoCardEmptyState(
                            symbol: "ladybug.fill",
                            title: "No crash reports",
                            message: "Crash reports recorded on this device appear here."
                        )
                        .frame(minHeight: 180)
                    } else {
                        ForEach(manager.reports) { report in


                                FormNavigationLink {
                                    HakoCrashReportDetailView(report: report)
                                } label: {
                                    reportLabel(report)
                                }
                                .accessibilityIdentifier("hako.report.\(report.id)")

                        }
                    }
                }
            }
        }
        .overlay {
            if isLoading {
                ProgressView()
            }
        }
        .onAppear {
            Task {
                await manager.refresh()
                isLoading = false
            }
        }
        .alert($alert)


        .toolbar {
                    ToolbarItem {
                        CrashReportToolbarMenu(manager: manager)
                    }
                }

    }

    private func reportLabel(_ report: CrashReport) -> some View {


            HakoNavigationRow(
                title: report.date.formatted(date: .abbreviated, time: .shortened),
                subtitle: report.origin == ReportArchive.tvOSDeviceOrigin
                    ? String(localized: "From Apple TV")
                    : String(localized: "From this device"),
                systemImage: "ladybug.fill",
                tint: HakoAccentRole.neutral.color,
                badge: report.isRead ? nil : String(localized: "Unread"),
                badgeEmphasis: .info
            )

    }
}


    private struct NetworkExtensionCrashMenu: View {
        @EnvironmentObject private var environments: ExtensionEnvironments
        @ObservedObject var profile: ExtensionProfile

        var body: some View {
            if profile.status.isConnectedStrict {
                Menu("NetworkExtension") {
                    Button("Go Crash") {
                        try? LibboxNewStandaloneCommandClient()?.triggerGoCrash()
                        Task {
                            try? await Task.sleep(nanoseconds: NSEC_PER_SEC)
                            await environments.crashReportManager.refresh()
                        }
                    }
                    Button("Native Crash") {
                        try? LibboxNewStandaloneCommandClient()?.triggerNativeCrash()
                        Task {
                            try? await Task.sleep(nanoseconds: NSEC_PER_SEC)
                            await environments.crashReportManager.refresh()
                        }
                    }
                }
            }
        }
    }


    private struct CrashReportToolbarMenu: View {
        @EnvironmentObject private var environments: ExtensionEnvironments
        @ObservedObject var manager: CrashReportManager

        var body: some View {
            if !manager.reports.isEmpty || Variant.inDebug {
                Menu {
                    if Variant.inDebug {
                        Menu {
                            Menu("Application") {
                                Button("Go Crash") {
                                    LibboxTriggerGoPanic()
                                }
                                Button("Native Crash") {
                                    DispatchQueue.global().asyncAfter(deadline: .now() + .milliseconds(200)) {
                                        fatalError("debug native crash")
                                    }
                                }
                            }
                            if let profile = environments.extensionProfile {
                                NetworkExtensionCrashMenu(profile: profile)
                            }


                        } label: {
                            Label("Crash Trigger", systemImage: "ant.fill")
                        }
                    }
                    if !manager.reports.isEmpty {
                        Button(role: .destructive) {
                            Task {
                                await manager.deleteAll()
                            }
                        } label: {
                            Label("Delete All", systemImage: "trash.fill")
                        }
                    }
                } label: {
                    Label("Others", systemImage: "line.3.horizontal.circle")
                }
            }
        }
    }

