//
//  HakoEditorToolbarView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Profile/EditorToolbarView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

//  The original wraps this page in `#if os(iOS) || os(macOS)` (`ApplicationLibrary/Views/Profile/EditorToolbarView.swift`: line 3, closed at `149`), and the symbols it
//  reads are declared under that same condition. Restored by
//  `scripts/dev/restore_file_level_guards.py`, which reads the condition out of the
//  original rather than keeping a list; the body is the port's own and is re-indented
//  once, not rewritten.
//
#if os(iOS) || os(macOS)
    import SwiftUI


        public struct HakoEditorToolbarView: View {
            let canUndo: Bool
            let canRedo: Bool
            let onUndo: () -> Void
            let onRedo: () -> Void
            let onFormat: () -> Void
            let onInsertSymbol: (String) -> Void
            let configurationError: String?
            let onDismissError: () -> Void

            public init(
                canUndo: Bool,
                canRedo: Bool,
                onUndo: @escaping () -> Void,
                onRedo: @escaping () -> Void,
                onFormat: @escaping () -> Void,
                onInsertSymbol: @escaping (String) -> Void,
                configurationError: String?,
                onDismissError: @escaping () -> Void
            ) {
                self.canUndo = canUndo
                self.canRedo = canRedo
                self.onUndo = onUndo
                self.onRedo = onRedo
                self.onFormat = onFormat
                self.onInsertSymbol = onInsertSymbol
                self.configurationError = configurationError
                self.onDismissError = onDismissError
            }

            public var body: some View {
                VStack(spacing: 2) {
                    if let error = configurationError {
                        errorBanner(error)
                    }
                    symbolBar
                }
            }

            private func errorBanner(_ error: String) -> some View {
                HStack {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .foregroundStyle(.red)
                    Text(error)
                        .font(.footnote)
                        .lineLimit(2)
                    Spacer()
                    Button {
                        onDismissError()
                    } label: {
                        Image(systemName: "xmark")
                            .font(.footnote.weight(.semibold))
                    }
                    .buttonStyle(.plain)
                }
                .padding(.horizontal, 12)
                .padding(.vertical, 8)

                    .background(HakoProductPalette.system.card, in: RoundedRectangle(cornerRadius: HakoTheme.Radius.card, style: .continuous))


                    .padding(.horizontal, 8)
            }

            private var symbolBar: some View {
                ScrollView(.horizontal, showsIndicators: false) {
                    HStack(spacing: 4) {
                        actionButtons
                        Divider().frame(height: 24).padding(.horizontal, 4)
                        symbolButtons
                    }
                    .padding(.horizontal, 8)
                    .padding(.vertical, 6)
                }

                .background(HakoProductPalette.system.card, in: RoundedRectangle(cornerRadius: HakoTheme.Radius.card, style: .continuous))


                .padding(.horizontal, 8)
                .padding(.bottom, 8)
            }

            private var actionButtons: some View {
                HStack(spacing: 4) {
                    Button {
                        onUndo()
                    } label: {
                        Label("Undo", systemImage: "arrow.uturn.backward")
                    }
                    .disabled(!canUndo)

                    Button {
                        onRedo()
                    } label: {
                        Label("Redo", systemImage: "arrow.uturn.forward")
                    }
                    .disabled(!canRedo)

                    Button {
                        onFormat()
                    } label: {
                        Label("Format", systemImage: "text.alignleft")
                    }
                }
                .hakoSecondaryActionButtonStyle()
            }

            private var symbolButtons: some View {
                HStack(spacing: 2) {
                    ForEach(primarySymbols, id: \.self) { symbol in
                        symbolButton(symbol)
                    }
                    ForEach(secondarySymbols, id: \.self) { symbol in
                        symbolButton(symbol)
                    }
                }
                .hakoSecondaryActionButtonStyle()
            }

            private var primarySymbols: [String] {
                ["\"", ":", ",", "{", "}", "[", "]"]
            }

            private var secondarySymbols: [String] {
                ["true", "false"]
            }

            private func symbolButton(_ symbol: String) -> some View {
                Button {
                    onInsertSymbol(symbol)
                } label: {
                    Text(symbol)
                        .font(.system(.body, design: .monospaced).weight(.medium))

                        .frame(minWidth: symbol.count > 1 ? nil : 32, minHeight: 32)


                }
            }
        }


#endif
