//
//  HakoFontPickerView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Setting/HakoFontPickerView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//


    import Library
    import SwiftUI
    import UniformTypeIdentifiers


#if canImport(UIKit)
    import UIKit
#endif


    public struct HakoFontPickerView: View {
        private let pool: [String]
        private let onSelect: (String) -> Void

        @State private var selected: String
        @State private var searchText: String = ""
        @Environment(\.dismiss) private var dismiss


            @StateObject private var fontStore = ImportedFontStore.shared
            @State private var showFileImporter = false
            @State private var alert: AlertState?
            @State private var editMode: EditMode = .inactive


        public init(currentName: String, onSelect: @escaping (String) -> Void) {
            self.onSelect = onSelect
            _selected = State(initialValue: currentName)
            pool = Self.monospacedFamilies()
        }

        public var body: some View {
            List {
                if searchText.isEmpty {
                    Section {
                        familyRow(name: "", label: String(localized: "Follow Theme"))
                    }

                        if !fontStore.fonts.isEmpty {
                            Section("Imported") {
                                ForEach(fontStore.fonts) { font in
                                    familyRow(name: font.familyName, label: font.familyName)
                                }
                                .onDelete { offsets in
                                    let targets = offsets.map { fontStore.fonts[$0] }
                                    Task { await deleteImported(targets) }
                                }
                            }
                        }

                    ForEach(groupedKeys, id: \.self) { letter in
                        Section(letter) {
                            ForEach(grouped[letter] ?? [], id: \.self) { family in
                                familyRow(name: family, label: family)
                            }
                        }
                    }
                } else {
                    Section("Fonts") {
                        ForEach(filteredFamilies, id: \.self) { family in
                            familyRow(name: family, label: family)
                        }
                    }
                }
            }
            .searchable(text: $searchText)
            .navigationTitle("Font")

                .navigationBarTitleDisplayMode(.inline)
                .environment(\.editMode, $editMode)
                .toolbar {
                    ToolbarItem(placement: .topBarTrailing) {
                        Menu {
                            Button {
                                showFileImporter = true
                            } label: {
                                Label("Import from File", systemImage: "doc.badge.plus")
                            }
                            if !fontStore.fonts.isEmpty {
                                Button {
                                    withAnimation {
                                        editMode = editMode.isEditing ? .inactive : .active
                                    }
                                } label: {
                                    Label(
                                        editMode.isEditing ? String(localized: "Done") : String(localized: "Manage Imported Fonts"),
                                        systemImage: "slider.horizontal.3"
                                    )
                                }
                            }
                        } label: {
                            Label("Others", systemImage: "ellipsis.circle")
                        }
                    }
                }
                .alert($alert)
                .fileImporter(
                    isPresented: $showFileImporter,
                    allowedContentTypes: [.font],
                    allowsMultipleSelection: true
                ) { result in
                    handleFontImport(result)
                }

        }

        private func familyRow(name: String, label: String) -> some View {
            Button {
                select(name)
            } label: {
                HStack {
                    Text(label)
                        .font(name.isEmpty ? .body : .custom(name, size: 17))
                        .foregroundStyle(.primary)
                    Spacer()
                    HakoSelectionMark(isSelected: selected == name)
                }
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
        }

        private var filteredFamilies: [String] {
            let query = searchText.lowercased()

                let imported = fontStore.fonts.map(\.familyName)
                let combined = Array(NSOrderedSet(array: imported + pool)) as? [String] ?? pool
                return combined.filter { $0.lowercased().contains(query) }


        }

        private var grouped: [String: [String]] {

                let importedNames = Set(fontStore.fonts.map(\.familyName))

            var result: [String: [String]] = [:]
            for family in pool {

                    if importedNames.contains(family) {
                        continue
                    }

                let first = family.first.map(String.init)?.uppercased() ?? "#"
                let key = first.first?.isLetter == true ? first : "#"
                result[key, default: []].append(family)
            }
            return result
        }

        private var groupedKeys: [String] {
            grouped.keys.sorted()
        }

        private func select(_ name: String) {
            selected = name
            onSelect(name)
            dismiss()
        }


            private func handleFontImport(_ result: Result<[URL], Error>) {
                do {
                    let urls = try result.get()
                    guard !urls.isEmpty else { return }
                    Task {
                        for url in urls {
                            do {
                                try await fontStore.importFile(from: url)
                            } catch {
                                alert = AlertState(action: "import font", error: error)
                                return
                            }
                        }
                    }
                } catch {
                    alert = AlertState(action: "import font", error: error)
                }
            }

            private func deleteImported(_ targets: [ImportedFont]) async {
                for font in targets {
                    do {
                        try await fontStore.delete(font)
                        if selected == font.familyName {
                            selected = ""
                        }
                    } catch {
                        alert = AlertState(action: "remove font", error: error)
                        return
                    }
                }
                if fontStore.fonts.isEmpty, editMode.isEditing {
                    withAnimation { editMode = .inactive }
                }
            }


        private static func monospacedFamilies() -> [String] {


                return UIFont.familyNames.filter { family in
                    UIFont.fontNames(forFamilyName: family).contains { name in
                        guard let font = UIFont(name: name, size: 12) else { return false }
                        return font.fontDescriptor.symbolicTraits.contains(.traitMonoSpace)
                    }
                }.sorted { $0.localizedCaseInsensitiveCompare($1) == .orderedAscending }


        }
    }

