//
//  HakoUSBIPServerView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/HakoUSBIPServerView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

@MainActor
public struct HakoUSBIPServerView: View {
    @ObservedObject var viewModel: USBIPStatusViewModel


    @Environment(\.dismiss) private var dismiss
    let serverTag: String

    public init(viewModel: USBIPStatusViewModel, serverTag: String) {
        self.viewModel = viewModel
        self.serverTag = serverTag
    }

    private var server: USBIPServerData? {
        viewModel.server(tag: serverTag)
    }

    private var navigationTitleKey: LocalizedStringKey {
        viewModel.servers.count > 1 ? "USB/IP: \(serverTag)" : "USB/IP"
    }

    public var body: some View {
        FormView {
            if let server {
                Section {
                    deviceSection(server)
                } header: {
                    Text("Devices")
                } footer: {
                    providerFooter
                }
            }
        }
        .navigationTitle(navigationTitleKey)

            .navigationBarTitleDisplayMode(.inline)


        .onChangeCompat(of: server == nil) { isNil in
            if isNil {
                dismiss()
            }
        }
    }

    @ViewBuilder
    private func deviceSection(_ server: USBIPServerData) -> some View {


            if server.devices.isEmpty {
                Text("No devices shared yet.")
                    .foregroundStyle(.secondary)
            } else {
                ForEach(server.devices) { device in
                    deviceLink(device)
                }
            }

    }

    private func deviceLink(_ device: USBSharedDeviceData) -> some View {
        let state = usbDeviceState(device.state)
        let label = deviceRowLabel(name: device.displayName, dotColor: state.color, stateLabel: state.label)


            return FormNavigationLink {
                USBIPDeviceView(device: device)
            } label: {
                label
            }

    }

    private func deviceRowLabel(name: String, dotColor: some ShapeStyle, stateLabel: LocalizedStringKey) -> some View {
        HStack(spacing: 6) {
            Image(systemName: "circle.fill")
                .font(.system(size: 8))
                .foregroundStyle(dotColor)
            Text(verbatim: "\(name):")
                .lineLimit(1)
                .truncationMode(.tail)
            Text(stateLabel)
                .foregroundStyle(.secondary)
                .lineLimit(1)
                .layoutPriority(1)
            Spacer(minLength: 0)
        }
    }


        private var providerFooter: some View {
            Text("To provide devices, use a Chromium-based browser with the sing-box dashboard, or the sing-box graphical client on macOS or Android.")
        }

}
