//
//  HakoNetworkQualityView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/NetworkQualityView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI

@MainActor
public struct HakoNetworkQualityView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @StateObject private var viewModel = NetworkQualityViewModel()

    public init() {}

    private var downloadActive: Bool {
        (viewModel.isRunning && !viewModel.serial && viewModel.phase >= LibboxNetworkQualityPhaseDownload && viewModel.phase < LibboxNetworkQualityPhaseDone)
            || viewModel.phase == LibboxNetworkQualityPhaseDownload
    }

    private func accuracyLabel(_ value: Int32) -> (label: String, color: Color) {
        switch value {
        case LibboxNetworkQualityAccuracyHigh:
            return (String(localized: "Confidence High"), .green)
        case LibboxNetworkQualityAccuracyMedium:
            return (String(localized: "Confidence Medium"), .yellow)
        default:
            return (String(localized: "Confidence Low"), .red)
        }
    }

    private var uploadActive: Bool {
        (viewModel.isRunning && !viewModel.serial && viewModel.phase >= LibboxNetworkQualityPhaseDownload && viewModel.phase < LibboxNetworkQualityPhaseDone)
            || viewModel.phase == LibboxNetworkQualityPhaseUpload
    }

    @ViewBuilder
    private func resultValue(_ value: String?, active: Bool, accuracy: (label: String, color: Color)? = nil) -> some View {
        if let value {
            HStack(spacing: 6) {
                if viewModel.isRunning, active {
                    ProgressView()
                        .controlSize(.small)
                }
                Text(value)
                if let accuracy {
                    Text(accuracy.label)
                        .font(.caption)
                        .foregroundColor(accuracy.color)
                }
            }
        } else if viewModel.isRunning, active {
            ProgressView()
                .controlSize(.small)
        } else {
            Text(verbatim: "-")
        }
    }

    public var body: some View {
        FormView {
            Section("Configuration") {


                    // The review's item on this page. `FormItem` is the platform's labelled row,
                    // and for a value this long the platform answers by putting it on its own
                    // line, indented - the row the review described as "an extra level of
                    // indentation". A URL is a paragraph, not a figure: it gets a plain row of
                    // its own, the title at the card's leading edge like every other row here,
                    // and the field's text left-aligned so a URL that wraps starts every line in
                    // the same place instead of each line right-aligning against the one above.
                    HStack(alignment: .firstTextBaseline, spacing: HakoTheme.Spacing.compact) {
                        Text("URL")
                            .lineLimit(1)
                            .layoutPriority(1)
                        Spacer(minLength: HakoTheme.Spacing.compact)
                        TextField(text: $viewModel.configURL) {}
                            .multilineTextAlignment(.leading)
                            .autocorrectionDisabled()

                            #if !os(macOS)
                            .textInputAutocapitalization(.never)
                            #endif
                            #if !os(macOS)
                            .keyboardType(.URL)
                            #endif

                    }

                Toggle("Serial", isOn: $viewModel.serial)
                    .disabled(viewModel.isRunning)
                Toggle("HTTP/3", isOn: $viewModel.http3)
                    .disabled(viewModel.isRunning)
                FormPicker(
                    String(localized: "Max Runtime"),
                    options: MaxRuntimeOption.allCases.map { FormPickerOption($0, $0.label) },
                    selection: $viewModel.maxRuntime
                )
                .disabled(viewModel.isRunning)
                if environments.remoteServer != nil {
                    HakoRemoteToolOutboundSection(commandClient: environments.commandClient, viewModel: viewModel)
                } else if let profile = environments.extensionProfile {
                    HakoToolOutboundSection(profile: profile, viewModel: viewModel)
                }
            }

            Section("Action") {
                if viewModel.isRunning {
                    FormButton {
                        viewModel.cancel()
                    } label: {
                        Label("Cancel Test", systemImage: "stop.fill")
                    }
                } else {
                    FormButton {
                        viewModel.requestStartTest(vpnConnected: environments.serviceAvailable)
                    } label: {
                        Label("Start Test", systemImage: "play.fill")
                    }
                }
            }

            if viewModel.phase >= 0 {
                Section("Results") {
                    FormTextItem("Idle Latency", "timer") {
                        resultValue(viewModel.idleLatencyMs > 0 ? "\(viewModel.idleLatencyMs) ms" : nil, active: viewModel.phase == LibboxNetworkQualityPhaseIdle)
                    }
                    FormTextItem("Download", "arrow.down.circle") {
                        resultValue(viewModel.downloadCapacity > 0 ? LibboxFormatBitrate(viewModel.downloadCapacity) : nil, active: downloadActive, accuracy: viewModel.phase == LibboxNetworkQualityPhaseDone ? accuracyLabel(viewModel.downloadCapacityAccuracy) : nil)
                    }
                    FormTextItem("Download RPM", "arrow.down.to.line") {
                        resultValue(viewModel.downloadRPM > 0 ? "\(viewModel.downloadRPM)" : nil, active: downloadActive, accuracy: viewModel.phase == LibboxNetworkQualityPhaseDone ? accuracyLabel(viewModel.downloadRPMAccuracy) : nil)
                    }
                    FormTextItem("Upload", "arrow.up.circle") {
                        resultValue(viewModel.uploadCapacity > 0 ? LibboxFormatBitrate(viewModel.uploadCapacity) : nil, active: uploadActive, accuracy: viewModel.phase == LibboxNetworkQualityPhaseDone ? accuracyLabel(viewModel.uploadCapacityAccuracy) : nil)
                    }
                    FormTextItem("Upload RPM", "arrow.up.to.line") {
                        resultValue(viewModel.uploadRPM > 0 ? "\(viewModel.uploadRPM)" : nil, active: uploadActive, accuracy: viewModel.phase == LibboxNetworkQualityPhaseDone ? accuracyLabel(viewModel.uploadRPMAccuracy) : nil)
                    }
                }
            }
        }
        .hakoNavigationChrome(title: String(localized: "Network Quality"))
        .task {
            await viewModel.loadPreferences()
        }
        .alert($viewModel.alert)
        .onDisappear {
            if viewModel.isRunning {
                viewModel.cancel()
            }
        }
    }
}

// The phone's outbound section is generic over the Hako copy of the protocol, but the view model is
// shared: `NetworkQualityViewModel` lives in `Tools/` and an iPad loads it too, so it declares its
// conformance to the original `OutboundSelectable` there and cannot name a Hako type. The two
// protocols are requirement-identical - the migration renames module-scope types, and this one
// carries three members that the shared one already satisfies - so the phone supplies the second
// conformance here, next to the one call that needs it, rather than editing a shared file.
extension NetworkQualityViewModel: HakoOutboundSelectable {}
