//
//  HakoRemoteControlView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/RemoteControl/HakoRemoteControlView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import SwiftUI

@MainActor
public struct HakoRemoteControlView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @State private var isLoading = true
    @State private var servers: [RemoteServer] = []
    @State private var alert: AlertState?


        @State private var editingServer: RemoteServer?
        @State private var showNewServer = false


    public init() {}

    public var body: some View {
        content
            .alert($alert)
            .onAppear {
                Task {
                    await reload()
                }
            }
    }


        private var content: some View {
            Group {
                if isLoading {
                    ProgressView()
                        .frame(maxWidth: .infinity, maxHeight: .infinity)
                } else {
                    FormView {
                        serversSection
                    }
                }
            }
            .hakoNavigationChrome(title: String(localized: "Remote Control"))
            .sheet(isPresented: $showNewServer) {
                serverSheet(nil)
            }
            .sheet(item: $editingServer) { server in
                serverSheet(server)
            }
        }

        private var serversSection: some View {
            Section {
                if servers.isEmpty {
                    Text("No servers")
                        .foregroundStyle(.secondary)
                        .font(.callout)
                } else {
                    ForEach(servers) { server in
                        serverRow(server)
                    }
                }
            } header: {
                HStack {
                    Text("Servers")
                    Spacer()
                    Button {
                        showNewServer = true
                    } label: {
                        Label("New Server", systemImage: "plus.circle.fill")
                            .labelStyle(.iconOnly)
                    }


                }
            }
        }

        private func serverRow(_ server: RemoteServer) -> some View {
            Button {
                editingServer = server
            } label: {
                HStack {
                    VStack(alignment: .leading, spacing: 4) {
                        Text(server.displayName)
                            .fontWeight(.medium)
                        if server.name != nil {
                            Text(server.url)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                    Spacer()
                    Image(systemName: "chevron.right")
                        .foregroundStyle(.secondary)
                        .font(.caption)
                }
                .contentShape(Rectangle())
            }


            .foregroundStyle(.primary)

        }

        @ViewBuilder
        private func serverSheet(_ server: RemoteServer?) -> some View {


                NavigationSheet(title: server == nil ? String(localized: "New Server") : String(localized: "Edit Server")) {
                    EditRemoteServerView(server) {
                        await reload()
                    }
                }

        }


    private func reload() async {
        do {
            servers = try await RemoteServerManager.list()
        } catch {
            alert = AlertState(action: "load server list", error: error)
        }
        isLoading = false
    }
}

