//
//  HakoTerminalSessionContainerView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Terminal/TerminalSessionContainerView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//


#if canImport(GhosttyTerminal)
    import GhosttyTerminal
#endif
    import Library
    import SwiftUI


    #if canImport(GhosttyTerminal) && os(iOS)
    @MainActor
    struct HakoTerminalSessionContainerView: View {
        @StateObject private var sessionManager = TerminalSessionManager()
        private let initialSession: TailscaleSSHPresentedSession
        @Environment(\.dismiss) private var dismiss
        @Environment(\.openURL) private var openURL

        init(_ initialSession: TailscaleSSHPresentedSession) {
            self.initialSession = initialSession
        }

        var body: some View {
            ZStack {
                ForEach(sessionManager.sessions) { managed in
                    let isActive = managed.id == sessionManager.activeSessionID
                    HakoTerminalSessionContentView(
                        viewModel: managed.viewModel,
                        presentedSession: managed.presentedSession,
                        isActive: isActive,
                        onCloseSession: { sessionManager.closeSession(id: managed.id) }
                    )
                    .opacity(isActive ? 1 : 0)
                    .zIndex(isActive ? 1 : 0)
                    .allowsHitTesting(isActive)
                    .onAppear {
                        setupCallbacks(for: managed)
                    }
                }
            }
            .navigationTitle(sessionManager.activeDisplayTitle)
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button {
                        dismiss()
                    } label: {
                        Image(systemName: "chevron.backward")
                    }
                }
                ToolbarItem(placement: .primaryAction) {
                    TerminalSessionMenuButton(sessionManager: sessionManager)
                }
            }
            .background(
                Button(action: {
                    if let id = sessionManager.activeSessionID {
                        sessionManager.closeSession(id: id)
                    }
                }) {}
                    .keyboardShortcut("w", modifiers: .command)
                    .opacity(0)
                    .frame(width: 0, height: 0)
                    .accessibilityHidden(true)
            )
            .background(
                Button(action: {
                    sessionManager.createDuplicateSession()
                }) {}
                    .keyboardShortcut("n", modifiers: .command)
                    .opacity(0)
                    .frame(width: 0, height: 0)
                    .accessibilityHidden(true)
            )
            .onAppear {
                sessionManager.onDismissAll = { dismiss() }
                sessionManager.addSession(from: initialSession)
            }
            .onDisappear {
                sessionManager.disconnectAll()
            }
        }

        private func setupCallbacks(for managed: TerminalSessionManager.ManagedSession) {
            managed.viewModel.extras.onOpenURL = { urlString, _ in
                guard let url = URL(string: urlString) else { return }
                openURL(url)
            }
            #if !targetEnvironment(macCatalyst)
                managed.viewModel.extras.onCommandKey = { key in
                    switch key {
                    case "n":
                        sessionManager.createDuplicateSession()
                        return true
                    case "w":
                        sessionManager.closeSession(id: managed.id)
                        return true
                    default:
                        return false
                    }
                }
            #endif
        }
    }
    #endif

