//
//  HakoReportShared.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Tools/ReportShared.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI
import UniformTypeIdentifiers


#if canImport(UIKit)
    import UIKit
#endif


struct HakoReportLabel: View {
    let date: Date
    let isRead: Bool
    let origin: String?

    var body: some View {
        HStack(spacing: 8) {
            Circle()
                .fill(isRead ? .clear : .blue)
                .frame(width: 10, height: 10)
            VStack(alignment: .leading, spacing: 2) {
                Text(date, format: .dateTime)
                    .fontWeight(isRead ? .regular : .semibold)
                HStack(spacing: 4) {
                    Image(systemName: origin == ReportArchive.tvOSDeviceOrigin ? "appletv.fill" : Self.localDeviceIcon)
                    Text(origin == ReportArchive.tvOSDeviceOrigin ? "Apple TV" : "Local")
                }
                .font(.caption)
                .foregroundStyle(.secondary)
            }
        }
    }


        private static let localDeviceIcon = "iphone"


}

@MainActor
struct HakoReportFileContentView: View {
    @State private var content = ""
    @State private var isLoading = true

    let fileURL: URL
    let displayName: String

    var body: some View {
        Group {
            if isLoading {
                ProgressView()
                    .onAppear {
                        Task {
                            content = await Self.loadContent(fileURL: fileURL)
                            isLoading = false
                        }
                    }
            } else if content.isEmpty {
                HakoEmptyState(
                    symbol: "doc.text",
                    title: "Empty",
                    message: "This report has no content."
                )
            } else {
                PlainTextView(content: content)
            }
        }
        .hakoNavigationChrome(title: displayName)
    }

    private static let maxContentBytes: UInt64 = 2 * 1024 * 1024

    private nonisolated static func loadContent(fileURL: URL) async -> String {
        await BlockingIO.run {
            guard let handle = try? FileHandle(forReadingFrom: fileURL) else {
                return ""
            }
            defer { try? handle.close() }
            let size = (try? handle.seekToEnd()) ?? 0
            var truncated = false
            if size > maxContentBytes {
                truncated = true
                try? handle.seek(toOffset: size - maxContentBytes)
            } else {
                try? handle.seek(toOffset: 0)
            }
            guard let data = try? handle.readToEnd(), var content = String(data: data, encoding: .utf8) else {
                return ""
            }
            if truncated {
                if let lineStart = content.firstIndex(of: "\n") {
                    content = String(content[content.index(after: lineStart)...])
                }
                content = "…\n" + content
            }
            return content
        }
    }
}


    @MainActor
    func createReportZip(reportID: String, fileURL: URL, cacheSubdirectory: String, includeConfig: Bool, includeLog: Bool, encrypt: Bool) async throws -> URL {
        try await BlockingIO.run {
            let tempDir = FilePath.cacheDirectory.appendingPathComponent(cacheSubdirectory, isDirectory: true)
            try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
            let tempURL = tempDir.appendingPathComponent(encrypt ? "\(reportID).zip.age" : "\(reportID).zip")
            try? FileManager.default.removeItem(at: tempURL)
            let strippedURL = tempDir.appendingPathComponent(reportID, isDirectory: true)
            try? FileManager.default.removeItem(at: strippedURL)
            try FileManager.default.copyItem(at: fileURL, to: strippedURL)
            try? FileManager.default.removeItem(at: strippedURL.appendingPathComponent(ReportArchive.readMarkerFileName))
            if !includeConfig {
                try? FileManager.default.removeItem(at: strippedURL.appendingPathComponent(ReportArchive.configFileName))
            }
            if !includeLog {
                try? FileManager.default.removeItem(at: strippedURL.appendingPathComponent(ReportArchive.goLogFileName))
                try? FileManager.default.removeItem(at: strippedURL.appendingPathComponent(ReportArchive.nativeLogFileName))
            }
            var error: NSError?
            LibboxCreateZipArchive(strippedURL.path, tempURL.path, encrypt, &error)
            try? FileManager.default.removeItem(at: strippedURL)
            if let error {
                throw error
            }
            return tempURL
        }
    }

    enum HakoReportShareAction {
        case save
        case share
    }

    @MainActor
    struct HakoReportSharePopup: View {
        @Environment(\.dismiss) private var dismiss

        let hasConfig: Bool
        let hasLog: Bool
        @Binding var includeConfig: Bool
        @Binding var includeLog: Bool
        @Binding var useAgeEncryption: Bool
        let onSave: () -> Void
        let onShare: () -> Void

        var body: some View {
            NavigationSheet(title: "Share", size: .medium) {
                FormView {
                    if hasConfig || hasLog {
                        Section {
                            if hasLog {
                                Toggle("With Log", isOn: $includeLog)
                            }
                            if hasConfig {
                                Toggle("With Configuration", isOn: $includeConfig)
                            }
                        } footer: {
                            if hasLog {
                                Text("Logs and configuration files may contain private content and should not be made public.")
                            } else {
                                Text("Configuration files may contain private content and should not be made public.")
                            }
                        }
                    }
                    Section {
                        Toggle("Encrypt with age for Project S", isOn: $useAgeEncryption)
                    } footer: {
                        Text("[age](https://github.com/filosottile/age) is a modern and secure asymmetric encryption tool. When enabled, the zip file is encrypted with this project's public key so it can be posted publicly, e.g. in GitHub issues.")
                    }
                    Section {
                        FormButton {
                            onSave()
                            dismiss()
                        } label: {
                            Label("Save", systemImage: "square.and.arrow.down")
                        }
                        FormButton {
                            onShare()
                            dismiss()
                        } label: {
                            Label("Share", systemImage: "square.and.arrow.up")
                        }
                        .keyboardShortcut(.defaultAction)
                    }
                }
                .hakoModalClose()
            }
        }
    }

    struct HakoReportZipDocument: FileDocument {
        static var readableContentTypes: [UTType] {
            [.zip, .data]
        }

        private let url: URL

        init(url: URL) {
            self.url = url
        }

        init(configuration: ReadConfiguration) throws {
            guard let data = configuration.file.regularFileContents else {
                throw CocoaError(.fileReadCorruptFile)
            }
            let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
            try data.write(to: tempURL)
            url = tempURL
        }

        func fileWrapper(configuration _: WriteConfiguration) throws -> FileWrapper {
            try FileWrapper(url: url)
        }
    }


        // `#if os(iOS)`, as the original had it. `UIApplication` and `UIWindowScene` are not in the macOS
        // SDK, and this file is in the shared target - so without the guard the macOS compiler is asked to
        // parse a function it cannot resolve. Migration resolved the original's `#if os(iOS)` here and kept
        // the body, which reads as "port the phone's version" but produces a file that no longer compiles
        // for the other platforms the same target serves.
        #if os(iOS)
            @MainActor
            func presentShareSheet(_ item: URL) {
                guard let windowScene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
                      let rootViewController = windowScene.keyWindow?.rootViewController
                else {
                    return
                }
                var topViewController = rootViewController
                while let presented = topViewController.presentedViewController {
                    topViewController = presented
                }
                topViewController.present(
                    UIActivityViewController(activityItems: [item], applicationActivities: nil),
                    animated: true
                )
            }
        #endif

