//
//  HakoOnDemandRulesView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Setting/OnDemandRulesView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Foundation
import Library
import SwiftUI

private enum OnDemandMode: String, CaseIterable, Identifiable {
    case disabled
    case alwaysOn
    case enabled

    var id: String {
        rawValue
    }

    var name: String {
        switch self {
        case .disabled: String(localized: "Disabled")
        case .alwaysOn: String(localized: "Always On")
        case .enabled: String(localized: "Enabled")
        }
    }

    var description: String {
        switch self {
        case .disabled: String(localized: "VPN will not connect automatically.")
        case .alwaysOn: String(localized: "Automatically connect VPN on any network.")
        case .enabled: String(localized: "Automatically connect or disconnect VPN based on rules.")
        }
    }
}

public struct HakoOnDemandRulesView: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @State private var isLoading = true
    @State private var alert: AlertState?
    @State private var mode: OnDemandMode = .disabled
    @State private var rules: [OnDemandRule] = []
    @State private var editingRule: OnDemandRule?
    @State private var isAddingRule = false
    @State private var loadTask: Task<Void, Never>?

        @State private var editMode: EditMode = .inactive


    public init() {}

    /// The page the manual names as the golden sample for every other settings page.
    ///
    /// The structure is the one all of them now share: a back control, a centred title,
    /// the page's own actions in the bar, then captioned cards of rows with one footnote
    /// where a footnote is needed, then the destructive action on its own at the end.
    ///
    /// What it replaces put each control in whatever container was nearest: a bare
    /// `Section` for the mode with the description as its footer, a second section whose
    /// header was an `HStack` holding a `plus.circle.fill` button, a third holding the
    /// reset, and an `EditButton` in the bar that the page never needed - reordering and
    /// deleting are already the row's own affordances.
    public var body: some View {
        HakoSettingsScaffold(
            title: String(localized: "On Demand"),
            actions: {
                HakoToolbarAction(
                    systemImage: "plus",
                    label: String(localized: "Add rule"),
                    isEnabled: mode == .enabled
                ) {
                    isAddingRule = true
                }
            }
        ) {
            if isLoading {
                HakoLoadingState()
                    .onAppear {
                        loadTask = Task {
                            await loadSettings()
                        }
                    }
            } else {
                modeSection
                if mode == .enabled {
                    rulesSection
                }
                resetSection
            }
        }
        .onDisappear {
            loadTask?.cancel()
        }
        .alert($alert)

        .platformSheet(isPresented: $isAddingRule) {
            OnDemandRuleEditView(rule: OnDemandRule(), isNew: true) { newRule in
                rules.append(newRule)
                Task {
                    await saveRules()
                }
            }
        }
        .platformSheet(item: $editingRule) { rule in
            OnDemandRuleEditView(rule: rule, isNew: false) { updatedRule in
                if let index = rules.firstIndex(where: { $0.id == updatedRule.id }) {
                    rules[index] = updatedRule
                    Task {
                        await saveRules()
                    }
                }
            }
        }

    }

    private var modeSection: some View {
        // Compact rows, and the explanation as the section's footnote - the review's shape.
        //
        // Each option used to carry its own description inside the row, so the card was three
        // two-line rows: tall, and as many heights as there were descriptions. The rows are the
        // standard settings row now and the footnote carries the *selected* option's meaning,
        // which is the one the reader is asking about, so nothing is said twice and the card
        // does not change height when the choice changes.
        HakoSettingsSection(
            String(localized: "Mode"),
            footnote: LocalizedStringKey(mode.description)
        ) {
            HakoSelectionRow(
                title: OnDemandMode.disabled.name,
                systemImage: "hand.raised.fill",
                tint: .secondary,
                isSelected: mode == .disabled
            ) {
                select(.disabled)
            }
            // The review's item: the same metric as the reset card below it, and as 更多.
            .hakoStandardRowMetric()


            HakoSelectionRow(
                title: OnDemandMode.alwaysOn.name,
                systemImage: "infinity",
                tint: HakoAccentRole.neutral.color,
                isSelected: mode == .alwaysOn
            ) {
                select(.alwaysOn)
            }
            // The review's item: the same metric as the reset card below it, and as 更多.
            .hakoStandardRowMetric()


            HakoSelectionRow(
                title: OnDemandMode.enabled.name,
                systemImage: "list.bullet.rectangle",
                tint: HakoAccentRole.neutral.color,
                isSelected: mode == .enabled
            ) {
                select(.enabled)
            }
            // The review's item: the same metric as the reset card below it, and as 更多.
            .hakoStandardRowMetric()
        }
    }

    private func select(_ newMode: OnDemandMode) {
        guard mode != newMode else { return }
        mode = newMode
        Task {
            await saveMode(newMode)
        }
    }

    private var rulesSection: some View {
        HakoSettingsSection(
            String(localized: "Rules"),
            footnote: "Rules are evaluated in order from top to bottom. The first matching rule determines the action."
        ) {
            if rules.isEmpty {
                HakoEmptyState(
                    symbol: "text.badge.plus",
                    title: "No rules yet",
                    message: "Add a rule to decide when the tunnel connects."
                )
            } else {
                ForEach(Array(rules.enumerated()), id: \.element.id) { index, rule in
                    if index > 0 {
                    }
                    HakoNavigationRow(
                        title: rule.action.name,
                        subtitle: ruleDescription(rule),
                        systemImage: "arrow.triangle.branch",
                        tint: HakoAccentRole.neutral.color
                    )
                    .contentShape(Rectangle())
                    .onTapGesture {
                        editingRule = rule
                    }
                    .contextMenu {
                        Button(role: .destructive) {
                            rules.removeAll { $0.id == rule.id }
                            Task {
                                await saveRules()
                            }
                        } label: {
                            Label("Delete", systemImage: "trash")
                        }
                    }
                }
                .onMove { from, to in
                    rules.move(fromOffsets: from, toOffset: to)
                    Task {
                        await saveRules()
                    }
                }
                .onDelete { offsets in
                    rules.remove(atOffsets: offsets)
                    Task {
                        await saveRules()
                    }
                }
            }
        }
    }

    private var resetSection: some View {
        HakoSettingsSection {
            HakoDestructiveRow(
                String(localized: "Reset On Demand Rules"),
                subtitle: String(localized: "Use the defaults the client ships with."),
                systemImage: "eraser.fill"
            ) {
                Task {
                    do {
                        try await SharedPreferences.resetOnDemandRules()
                        await updateService()
                        isLoading = true
                    } catch {
                        alert = AlertState(action: "reset on-demand rules", error: error)
                    }
                }
            }
        }
    }

    private func ruleDescription(_ rule: OnDemandRule) -> String {
        var parts: [String] = []

        if rule.interfaceType != .any {
            parts.append(rule.interfaceType.name)
        }

        if !rule.ssidMatch.isEmpty {
            let ssids = rule.ssidMatch.prefix(2).joined(separator: ", ")
            if rule.ssidMatch.count > 2 {
                parts.append("SSID: \(ssids) +\(rule.ssidMatch.count - 2)")
            } else {
                parts.append("SSID: \(ssids)")
            }
        }

        if !rule.dnsSearchDomainMatch.isEmpty {
            parts.append("DNS Domain")
        }

        if !rule.dnsServerAddressMatch.isEmpty {
            parts.append("DNS Server")
        }

        if !rule.probeURL.isEmpty {
            parts.append("Probe URL")
        }

        if rule.action == .evaluateConnection, !rule.connectionRules.isEmpty {
            parts.append("\(rule.connectionRules.count) connection rule(s)")
        }

        if parts.isEmpty {
            return "All networks"
        }
        return parts.joined(separator: " · ")
    }

    private func saveMode(_ newMode: OnDemandMode) async {
        let alwaysOn = newMode == .alwaysOn
        let onDemandEnabled = newMode == .enabled
        await SharedPreferences.alwaysOn.set(alwaysOn)
        await SharedPreferences.onDemandEnabled.set(onDemandEnabled)
        await updateService()
    }

    private func updateService() async {
        guard let profile = environments.extensionProfile, profile.status.isConnected else {
            return
        }
        do {
            let enabled = mode != .disabled
            try await profile.updateOnDemand(enabled: enabled, useDefaultRules: mode == .alwaysOn)
        } catch {
            alert = AlertState(action: "update on-demand rules", error: error)
        }
    }

    private func saveRules() async {
        await SharedPreferences.onDemandRules.set(rules)
        let savedRules = await SharedPreferences.onDemandRules.get()
        if savedRules != rules {
            alert = AlertState(errorMessage: String(localized: "Failed to save rules"))
            return
        }
        await updateService()
    }

    private func loadSettings() async {
        let alwaysOn = await SharedPreferences.alwaysOn.get()
        let onDemandEnabled = await SharedPreferences.onDemandEnabled.get()
        if alwaysOn {
            mode = .alwaysOn
        } else if onDemandEnabled {
            mode = .enabled
        } else {
            mode = .disabled
        }
        rules = await SharedPreferences.onDemandRules.get()
        isLoading = false
    }
}

private struct OnDemandRuleEditView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var rule: OnDemandRule
    private let onSave: (OnDemandRule) -> Void
    private let isNew: Bool

    @State private var editingConnectionRule: EvaluateConnectionRule?
    @State private var isAddingConnectionRule = false

    private var isProbeURLValid: Bool {
        guard !rule.probeURL.isEmpty else { return true }
        guard let url = URL(string: rule.probeURL),
              let scheme = url.scheme?.lowercased(),
              scheme == "http" || scheme == "https" else { return false }
        return true
    }

    init(rule: OnDemandRule, isNew: Bool, onSave: @escaping (OnDemandRule) -> Void) {
        _rule = State(initialValue: rule)
        self.onSave = onSave
        self.isNew = isNew
    }

    var body: some View {
        Form {
            actionSection
            conditionsSection
            if rule.action == .evaluateConnection {
                connectionRulesSection
            }


        }
        .navigationTitle(isNew ? "New Rule" : "Edit Rule")

            #if !os(macOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif


        .toolbar {
            ToolbarItem(placement: .cancellationAction) {
                Button("Cancel") {
                    dismiss()
                }
            }
            ToolbarItem(placement: .confirmationAction) {
                Button(isNew ? "Create" : "Save") {
                    onSave(rule)
                    dismiss()
                }
                .disabled(!isProbeURLValid)
            }
        }


        .platformSheet(isPresented: $isAddingConnectionRule, size: .small) {
            EvaluateConnectionRuleEditView(rule: EvaluateConnectionRule()) { newRule in
                rule.connectionRules.append(newRule)
            }
        }
        .platformSheet(item: $editingConnectionRule, size: .small) { connRule in
            EvaluateConnectionRuleEditView(rule: connRule) { updatedRule in
                if let index = rule.connectionRules.firstIndex(where: { $0.id == updatedRule.id }) {
                    rule.connectionRules[index] = updatedRule
                }
            }
        }
    }

    private var actionSection: some View {
        Section {
            FormPicker(
                String(localized: "Action"),
                options: OnDemandRuleAction.allCases.map { FormPickerOption($0, $0.name) },
                selection: $rule.action
            )

            .pickerStyle(.menu)


            FormPicker(
                String(localized: "Interface Type"),
                options: OnDemandRuleInterfaceType.availableCases.map { FormPickerOption($0, $0.name) },
                selection: $rule.interfaceType
            )

            .pickerStyle(.menu)

        } header: {
            Text("Action")
        } footer: {
            Text(rule.action.actionDescription)
        }
    }

    private var conditionsSection: some View {
        Section {
            StringListSection(title: "SSID Match", placeholder: "Add SSID", items: $rule.ssidMatch)
            StringListSection(title: "DNS Search Domain", placeholder: "Add domain", items: $rule.dnsSearchDomainMatch)
            StringListSection(title: "DNS Server Address", placeholder: "Add DNS server IP", items: $rule.dnsServerAddressMatch)
            probeURLSection
        } header: {
            Text("Conditions")
        } footer: {
            Text("All specified conditions must match for the rule to apply. Leave empty to match any network.")
        }
    }

    private var probeURLSection: some View {
        VStack(alignment: .leading) {
            HStack {
                Text("Probe URL")
                Spacer()
                TextField("http://...", text: $rule.probeURL)
                    .multilineTextAlignment(.trailing)

                    #if !os(macOS)
                    .keyboardType(.URL)
                    #endif
                    #if !os(macOS)
                    .textInputAutocapitalization(.never)
                    #endif

            }
            if !isProbeURLValid {
                Text("Only HTTP and HTTPS URLs are allowed")
                    .font(.caption)
                    .foregroundStyle(.red)
            }
        }
    }

    private var connectionRulesSection: some View {
        Section {
            if rule.connectionRules.isEmpty {
                Text("No connection rules. Add rules to specify which domains trigger VPN connection.")
                    .foregroundStyle(.secondary)
                    .font(.callout)
            } else {
                ForEach(rule.connectionRules) { connRule in
                    Button {
                        editingConnectionRule = connRule
                    } label: {
                        HStack {
                            VStack(alignment: .leading, spacing: 4) {
                                Text(connRule.action.name)
                                    .fontWeight(.medium)
                                if !connRule.matchDomains.isEmpty {
                                    Text(connRule.matchDomains.prefix(3).joined(separator: ", "))
                                        .font(.caption)
                                        .foregroundStyle(.secondary)
                                }
                            }
                            Spacer()

                                Image(systemName: "chevron.right")
                                    .foregroundStyle(.secondary)
                                    .font(.caption)

                        }
                        .contentShape(Rectangle())
                    }


                    .foregroundStyle(.primary)

                }
                .onMove { from, to in
                    rule.connectionRules.move(fromOffsets: from, toOffset: to)
                }
                .onDelete { offsets in
                    rule.connectionRules.remove(atOffsets: offsets)
                }
            }
        } header: {
            HStack {
                Text("Connection Rules")
                Spacer()
                Button {
                    isAddingConnectionRule = true
                } label: {
                    Image(systemName: "plus.circle.fill")
                }


            }
        } footer: {
            Text("When action is 'Evaluate Connection', these rules determine whether to connect based on the destination host.")
        }
    }
}

private struct EvaluateConnectionRuleEditView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var rule: EvaluateConnectionRule
    private let onSave: (EvaluateConnectionRule) -> Void

    @State private var domainText = ""
    @State private var dnsServerText = ""
    @State private var dnsServerError: String?

    private func isValidIPAddress(_ string: String) -> Bool {
        var sin = sockaddr_in()
        var sin6 = sockaddr_in6()
        return string.withCString { cstring in
            inet_pton(AF_INET, cstring, &sin.sin_addr) == 1 ||
                inet_pton(AF_INET6, cstring, &sin6.sin6_addr) == 1
        }
    }

    private var isProbeURLValid: Bool {
        guard !rule.probeURL.isEmpty else { return true }
        guard let url = URL(string: rule.probeURL),
              let scheme = url.scheme?.lowercased(),
              scheme == "http" || scheme == "https" else { return false }
        return true
    }

    private var canSave: Bool {
        !rule.matchDomains.isEmpty && isProbeURLValid
    }

    init(rule: EvaluateConnectionRule, onSave: @escaping (EvaluateConnectionRule) -> Void) {
        _rule = State(initialValue: rule)
        self.onSave = onSave
    }

    var body: some View {
        Form {
            Section {
                FormPicker(
                    String(localized: "Action"),
                    options: EvaluateConnectionRuleAction.allCases.map { FormPickerOption($0, $0.name) },
                    selection: $rule.action
                )

                .pickerStyle(.menu)

            } header: {
                Text("Action")
            } footer: {
                if rule.action == .connectIfNeeded {
                    Text("Connect VPN if the destination is not directly accessible.")
                } else {
                    Text("Never connect VPN for matching domains.")
                }
            }

            Section {
                matchDomainsSection
            } header: {
                Text("Match Domains")
            } footer: {
                Text("Domains that trigger this rule. The rule matches if the destination host shares a suffix with any domain in this list.")
            }

            if rule.action == .connectIfNeeded {
                Section {
                    useDNSServersSection
                } header: {
                    Text("DNS Servers")
                } footer: {
                    Text("DNS servers to use for resolving the destination. If resolution fails, VPN is started.")
                }

                Section {
                    HStack {
                        Text("Probe URL")
                        Spacer()
                        TextField("http://...", text: $rule.probeURL)
                            .multilineTextAlignment(.trailing)

                            #if !os(macOS)
                            .keyboardType(.URL)
                            #endif
                            #if !os(macOS)
                            .textInputAutocapitalization(.never)
                            #endif

                    }
                } header: {
                    Text("Probe URL")
                } footer: {
                    Text("If set, a request is sent to this URL. If it doesn't return HTTP 200, VPN is started.")
                }
            }
        }
        .navigationTitle("Connection Rule")

            #if !os(macOS)
            .navigationBarTitleDisplayMode(.inline)
            #endif

            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") {
                        dismiss()
                    }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        onSave(rule)
                        dismiss()
                    }
                    .disabled(!canSave)
                }
            }


    }

    @ViewBuilder
    private var matchDomainsSection: some View {

            ForEach(rule.matchDomains, id: \.self) { domain in
                HStack {
                    Text(domain)
                    Spacer()
                    Button {
                        rule.matchDomains.removeAll { $0 == domain }
                    } label: {
                        Image(systemName: "minus.circle.fill")
                            .foregroundStyle(.red)
                    }
                    .buttonStyle(.plain)
                }
            }
            HStack {
                TextField("Add domain (e.g., example.com)", text: $domainText)
                    .onSubmit {
                        addDomain()
                    }
                Button {
                    addDomain()
                } label: {
                    Image(systemName: "plus.circle.fill")
                }
                .buttonStyle(.plain)
                .disabled(domainText.isEmpty)
            }


    }

    @ViewBuilder
    private var useDNSServersSection: some View {

            ForEach(rule.useDNSServers, id: \.self) { server in
                HStack {
                    Text(server)
                    Spacer()
                    Button {
                        rule.useDNSServers.removeAll { $0 == server }
                    } label: {
                        Image(systemName: "minus.circle.fill")
                            .foregroundStyle(.red)
                    }
                    .buttonStyle(.plain)
                }
            }
            VStack(alignment: .leading) {
                HStack {
                    TextField("Add DNS server IP", text: $dnsServerText)
                        .onSubmit {
                            addDNSServer()
                        }
                    Button {
                        addDNSServer()
                    } label: {
                        Image(systemName: "plus.circle.fill")
                    }
                    .buttonStyle(.plain)
                    .disabled(dnsServerText.isEmpty)
                }
                if let error = dnsServerError {
                    Text(error)
                        .font(.caption)
                        .foregroundStyle(.red)
                }
            }


    }

    private func addDomain() {
        let trimmed = domainText.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty, !rule.matchDomains.contains(trimmed) {
            rule.matchDomains.append(trimmed)
        }
        domainText = ""
    }

    private func addDNSServer() {
        let trimmed = dnsServerText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            dnsServerText = ""
            return
        }
        guard isValidIPAddress(trimmed) else {
            dnsServerError = "Invalid IP address"
            return
        }
        dnsServerError = nil
        if !rule.useDNSServers.contains(trimmed) {
            rule.useDNSServers.append(trimmed)
        }
        dnsServerText = ""
    }
}

private struct StringListSection: View {
    let title: String
    let placeholder: String
    @Binding var items: [String]
    @State private var inputText = ""

    var body: some View {

            DisclosureGroup {
                ForEach(items, id: \.self) { item in
                    HStack {
                        Text(item)
                        Spacer()
                        Button {
                            items.removeAll { $0 == item }
                        } label: {
                            Image(systemName: "minus.circle.fill")
                                .foregroundStyle(.red)
                        }
                        .buttonStyle(.plain)
                    }
                }
                HStack {
                    TextField(placeholder, text: $inputText)
                        .onSubmit {
                            addItem()
                        }
                    Button {
                        addItem()
                    } label: {
                        Image(systemName: "plus.circle.fill")
                    }
                    .buttonStyle(.plain)
                    .disabled(inputText.isEmpty)
                }
            } label: {
                HStack {
                    Text(title)
                    Spacer()
                    if !items.isEmpty {
                        Text(verbatim: "\(items.count)")
                            .foregroundStyle(.secondary)
                    }
                }
            }


    }

    private func addItem() {
        let trimmed = inputText.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty, !items.contains(trimmed) {
            items.append(trimmed)
        }
        inputText = ""
    }
}

