//
//  HakoMacAppView.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Setting/MacAppView.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Library
import Libbox
import SwiftUI


public struct HakoAppView: View {
    private struct LanguageOption: Hashable {
        let code: String?
        let name: String
    }

    private static var supportedLanguages: [LanguageOption] {
        var options = [LanguageOption(code: nil, name: String(localized: "System Default"))]
        options.append(contentsOf: configuredLanguageCodes().map { code in
            let name = Locale(identifier: code).localizedString(forIdentifier: code) ?? code
            return LanguageOption(code: code, name: name)
        })
        return options
    }

    @State private var isLoading = true
    @State private var selectedLanguage: String?


    /// Provided on every platform: the system proxy's off-path restarts the tunnel, and that
    /// needs the profile. It used to be declared inside the desktop-only block, because only the
    /// desktop used it here.
    @EnvironmentObject private var environments: ExtensionEnvironments
    @State private var alert: AlertState?
    /// The tools page's top-right menu, moved here whole: its home-layout sheet and the remote
    /// control picker. The review's item is that a root page's chrome is not where either belongs.
    @State private var remoteServers: [RemoteServer] = []
    @State private var showCardManagement = false

    public init() {}
    public var body: some View {
        Group {
            if isLoading {
                ProgressView().onAppear {
                    Task {
                        await loadSettings()
                    }
                }
            } else {
                FormView {


                        // The three rows the review merged into this one card, in its order.
                        HakoSettingsSection {
                            // The language picker stays the menu it was on this platform, inside the
                            // client's own row: the current language is still the value on the
                            // right, and the choosing still happens in place.
                            HakoRowBody(
                                title: String(localized: "Language"),
                                systemImage: "globe",
                                tint: HakoAccentRole.neutral.color,
                                showsDisclosure: false
                            ) {
                                Picker("Language", selection: $selectedLanguage) {
                                    ForEach(Self.supportedLanguages, id: \.code) { language in
                                        Text(language.name).tag(language.code)
                                    }
                                }
                                .labelsHidden()
                                .onChangeCompat(of: selectedLanguage) { newValue in
                                    updateLanguage(newValue)
                                }
                            }
                            .hakoStandardRowMetric()

                            FormNavigationLink {
                                HakoGhosttyConfigurationView()
                            } label: {
                                HakoNavigationRow(
                                    title: String(localized: "Terminal Appearance"),
                                    subtitle: String(localized: "Colours and font for SSH sessions"),
                                    systemImage: "terminal.fill",
                                    tint: HakoAccentRole.neutral.color
                                )
                            }
                            .hakoStandardRowMetric()

                            FormButton {
                                showCardManagement = true
                            } label: {
                                HakoNavigationRow(
                                    title: String(localized: "Home Cards"),
                                    subtitle: String(localized: "What the home shows, and which device this client controls."),
                                    systemImage: "square.grid.2x2",
                                    tint: HakoAccentRole.neutral.color
                                )
                            }
                            .buttonStyle(HakoPushRowButtonStyle())
                            .hakoStandardRowMetric()
                            .accessibilityIdentifier("hako.settings.homeCards")
                        }


                    // Cache Size and Clear Cache lived here. The review moved both to 核心, where
                    // the client's own figures are read and its maintenance actions are taken;
                    // this page is about how the client looks and speaks.

                    // The menu the tools page used to carry. Its contents were the home-layout
                    // sheet and the remote control picker; both are settings, so both arrive on
                    // this page, in its own row language, with the menu's behaviour kept item for
                    // item - the sheet still opens, the active server still carries a checkmark,
                    // and the local device is still the way out of remote control.
                    HakoSettingsSection {
                        // The picker the menu showed only when there was somewhere to switch to,
                        // which is what its `if !servers.isEmpty` did.
                        if !remoteServers.isEmpty {
                            HakoRowDivider()
                            FormButton {
                                environments.exitRemoteControl()
                            } label: {
                                remoteControlRow(
                                    title: String(localized: "Local Device"),
                                    systemImage: "iphone",
                                    isActive: environments.remoteServer == nil
                                )
                            }
                            .buttonStyle(HakoPushRowButtonStyle())
                            .accessibilityIdentifier("hako.settings.remoteControl.local")

                            ForEach(remoteServers) { server in
                                HakoRowDivider()
                                FormButton {
                                    guard environments.remoteServer?.id != server.id else { return }
                                    environments.enterRemoteControl(server)
                                } label: {
                                    remoteControlRow(
                                        title: server.displayName,
                                        systemImage: "server.rack",
                                        isActive: environments.remoteServer?.id == server.id
                                    )
                                }
                                .buttonStyle(HakoPushRowButtonStyle())
                                .accessibilityIdentifier("hako.settings.remoteControl.server")
                            }

                            HakoRowDivider()
                            FormButton {
                                NotificationCenter.default.post(
                                    name: .navigateToSettingsPage,
                                    object: SettingsPage.remoteControl
                                )
                            } label: {
                                HakoToolRow(
                                    title: String(localized: "Manage Servers..."),
                                    systemImage: "slider.horizontal.3",
                                    tint: HakoAccentRole.neutral
                                )
                            }
                            .buttonStyle(HakoPushRowButtonStyle())
                            .accessibilityIdentifier("hako.settings.remoteControl.manage")
                        }
                    }


                }
            }
        }
        .alert($alert)


            // Named for what it configures rather than for the target it lives in, and it
            // wears the shared chrome: the same title treatment, the same back control and
            // the same tab-bar rule as a page on the scaffold.
            .hakoNavigationChrome(title: String(localized: "Client Settings"))
            // The review's high-priority item on this page: its one-line rows must be the size of
            // a first-level row. The container this page uses is shared with pages that are
            // frozen, so the metric is asked for here, on the page, rather than in the container.
            .environment(\.hakoCompactRows, true)
            .sheet(isPresented: $showCardManagement, content: {
                if #available(iOS 16.0, *) {
                    CardManagementSheet().presentationDetents([.large]).presentationDragIndicator(.visible)
                } else {
                    CardManagementSheet()
                }
            })
            .onAppear {
                Task { await reloadRemoteServers() }
            }
            .onReceive(NotificationCenter.default.publisher(for: .remoteServersUpdated)) { _ in
                Task { await reloadRemoteServers() }
            }
    }

    /// A remote control row: the name, and a checkmark when it is the one in use.
    private func remoteControlRow(title: String, systemImage: String, isActive: Bool) -> some View {
        HakoRowBody(
            title: title,
            systemImage: systemImage,
            tint: HakoAccentRole.neutral.color,
            showsDisclosure: false
        ) {
            if isActive {
                Image(systemName: "checkmark")
                    .font(.footnote.weight(.semibold))
                    .foregroundStyle(Color.accentColor)
            }
        }
    }

    private func reloadRemoteServers() async {
        remoteServers = await (try? RemoteServerManager.list()) ?? []
    }

    private func loadSettings() async {
        selectedLanguage = Self.currentLanguage()


        isLoading = false


    }


    private static func currentLanguage() -> String? {
        guard let selectedIdentifier = ApplicationLocale.selectedIdentifier else {
            return nil
        }
        let current = canonicalLanguageCode(selectedIdentifier)
        for language in supportedLanguages {
            guard let code = language.code else {
                continue
            }
            if current == code || current.hasPrefix("\(code)-") || current.hasPrefix("\(code)_") {
                return code
            }
        }
        return nil
    }


        private func updateLanguage(_ language: String?) {
            ApplicationLocale.setSelectedIdentifier(language)
            alert = AlertState(
                title: String(localized: "Restart Required"),
                message: String(localized: "Language will be changed after restarting the app.")
            )
        }


    private static func configuredLanguageCodes() -> [String] {
        let rawCodes: [String]
        if let configured = Bundle.main.object(forInfoDictionaryKey: "CFBundleLocalizations") as? [String],
           !configured.isEmpty
        {
            rawCodes = configured
        } else if let development = Bundle.main.developmentLocalization, !development.isEmpty {
            rawCodes = [development]
        } else {
            rawCodes = []
        }

        var seen = Set<String>()
        var codes: [String] = []
        for rawCode in rawCodes {
            let trimmed = rawCode.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else {
                continue
            }
            let canonical = canonicalLanguageCode(trimmed)
            guard !canonical.isEmpty, seen.insert(canonical).inserted else {
                continue
            }
            codes.append(canonical)
        }
        return codes
    }

    private static func canonicalLanguageCode(_ code: String) -> String {
        Locale.canonicalLanguageIdentifier(from: code)
    }


}
