//
//  HakoProfilePickerSheet.swift
//  ApplicationLibrary
//
//  The phone's configuration centre.
//
//  # Where this comes from
//
//  This is the fork's profile picker, from `hako-ui` @ `c1935cf`, resolved for iOS. It is the file
//  that carries the remaining-quota row: the item that reads the panel's `subscription-userinfo`
//  remainder out of the `ProfilePreview` snapshot the row already holds and prints it between the
//  configuration's type and its last-update time.
//
//  # Why it is a separate file from `ProfilePickerSheet`
//
//  An iPad and a Mac can both open the profile picker, and the requirement for both is upstream's
//  presentation with nothing added. The remaining-quota row is phone presentation. One file cannot
//  be both byte-identical to upstream and carry a new row, so
//  `ApplicationLibrary/Views/Dashboard/Cards/ProfilePickerSheet.swift` is restored to upstream and
//  this owns the phone's version.
//
//  The **data** chain is not forked: `SubscriptionInfo`, `RemoteProfileFetcher`,
//  `RemoteProfileRefresh`, `RemoteRefreshApplier` and the `add_subscription_info` migration are
//  shared, covered by `Tests/HakoSubscriptionUsage`, and read here through
//  `ProfilePreview.subscriptionInfo`.
//
//  # What is different from the official picker
//
//  The quota presentation, and the two layout properties that make room for it on the row's second
//  line. Everything else - the list, its edit mode, reorder, delete, QR share, export, and the editor
//  it presents - is upstream's, which is why this file is generated from the picker rather than
//  written out again. See `docs/HAKO-UI-MIGRATION-MATRIX.md`.
//
//  Generated by `scripts/dev/make_hako_profile_picker.py`, which is the only thing that should write
//  it.
//

import Library
import QRCode
import SwiftUI

@MainActor
struct HakoProfilePickerSheet: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @Environment(\.dismiss) private var dismiss

    @Binding var profileList: [ProfilePreview]
    @Binding var selectedProfileID: Int64

        @State private var editMode: EditMode = .inactive
    @State private var profileToEdit: Profile?
    @State private var alert: AlertState?
    @State private var showNewProfile = false
    @State private var isUpdatingAll = false

    private var isEditingActive: Bool {
            editMode.isEditing
    }

    var body: some View {
            if #available(iOS 26, *) {
                iOSBody
                    .environment(\.editMode, $editMode)
            } else {
                legacyIOSBody
                    .environment(\.editMode, $editMode)
            }
    }

        @available(iOS 26, *)
        private var iOSBody: some View {
            iOSListContent
                .toolbar {
                    ToolbarItem(placement: .primaryAction) {
                        // Add and edit belong together in one capsule, which is how the rest
                        // of this client presents a page's own actions. The add control used
                        // to exist only on the Home card, so a user already looking at their
                        // configurations had to close this sheet to add one.
                        HakoActionGroup {
                            if !remoteProfiles.isEmpty {
                                HakoActionItem(
                                    systemImage: "arrow.clockwise",
                                    label: String(localized: "Update All"),
                                    isBusy: isUpdatingAll
                                ) {
                                    Task {
                                        await updateAllProfiles()
                                    }
                                }
                                .accessibilityIdentifier("hako.profile.updateAll")
                            }
                            HakoActionItem(
                                systemImage: "plus",
                                label: String(localized: "Add Configuration")
                            ) {
                                showNewProfile = true
                            }
                            // The identifier the add entry point has always carried. It moved
                            // from the home's card, where it sat beside a picker and two other
                            // actions, to the centre, where adding a configuration belongs.
                            .accessibilityIdentifier("hako.profile.add")
                            HakoActionItem(
                                systemImage: editMode.isEditing ? "checkmark" : "pencil",
                                label: editMode.isEditing
                                    ? String(localized: "Done")
                                    : String(localized: "Edit")
                            ) {
                                withAnimation {
                                    editMode = editMode.isEditing ? .inactive : .active
                                }
                            }
                        }
                    }
                }
                .sheet(isPresented: $showNewProfile, onDismiss: {
                    environments.profileUpdate.send()
                }, content: {
                    ProfileCard.NewProfileNavigationView()
                        .environmentObject(environments)
                })
                .sheet(item: $profileToEdit) { profile in
                    NavigationSheet(title: "Edit Profile") {
                        HakoEditProfileView()
                            .environmentObject(profile)
                            .environmentObject(environments)
                            .hakoModalClose()
                    }
                }
                .alert($alert)
        }

        @available(iOS 26, *)
        @ViewBuilder
        private var iOSListContent: some View {
            if editMode.isEditing {
                iOSEditingList
            } else {
                iOSNormalList
            }
        }

        @available(iOS 26, *)
        private var iOSEditingList: some View {
            listContent
        }

        @available(iOS 26, *)
        private var iOSNormalList: some View {
            List {
                ForEach(profileList, id: \.id) { profile in
                    HakoProfilePickerRow(
                        profile: profile,
                        isSelected: profile.id == selectedProfileID,
                        alert: $alert,
                        onSelect: {
                            selectedProfileID = profile.id
                            dismiss()
                        },
                        onEdit: {
                            profileToEdit = profile.origin
                        },
                        onUpdate: {
                            await updateProfile(profile)
                        }
                    )
                    .environmentObject(environments)
                    .listRowBackground(Color.clear)
                    .listRowSeparator(.hidden)
                    .listRowInsets(EdgeInsets(top: 2, leading: 16, bottom: 2, trailing: 16))
                }
            }
            .listStyle(.plain)
        }

        private var legacyIOSBody: some View {
            legacyListContent
                .toolbar {
                    ToolbarItem(placement: .primaryAction) {
                        Button(editMode.isEditing ? "Done" : "Edit") {
                            withAnimation {
                                editMode = editMode.isEditing ? .inactive : .active
                            }
                        }
                    }
                }
                .sheet(item: $profileToEdit) { profile in
                    NavigationSheet(title: "Edit Profile") {
                        HakoEditProfileView()
                            .environmentObject(profile)
                            .environmentObject(environments)
                            .hakoModalClose()
                    }
                }
                .alert($alert)
        }


    private var listContent: some View {
            List {
                ForEach(profileList, id: \.id) { profile in
                    HakoProfilePickerRow(
                        profile: profile,
                        isSelected: profile.id == selectedProfileID,
                        alert: $alert,
                        onSelect: {
                            selectedProfileID = profile.id
                            dismiss()
                        },
                        onEdit: {
                            profileToEdit = profile.origin
                        },
                        onUpdate: {
                            await updateProfile(profile)
                        }
                    )
                    .environmentObject(environments)
                    .listRowBackground(Color.clear)
                    .listRowSeparator(.hidden)
                    .listRowInsets(EdgeInsets(top: 2, leading: 16, bottom: 2, trailing: 16))
                }
                .onMove(perform: moveProfile)
                .onDelete(perform: deleteProfile)
            }
            .listStyle(.plain)
    }

        @ViewBuilder
        private var legacyListContent: some View {
            if editMode.isEditing {
                legacyEditingList
            } else {
                legacyNormalList
            }
        }

        private var legacyEditingList: some View {
            List {
                ForEach(profileList, id: \.id) { profile in
                    LegacyProfilePickerRow(
                        profile: profile,
                        isSelected: profile.id == selectedProfileID,
                        alert: $alert,
                        onSelect: {
                            selectedProfileID = profile.id
                            dismiss()
                        },
                        onEdit: {
                            profileToEdit = profile.origin
                        },
                        onUpdate: {
                            await updateProfile(profile)
                        }
                    )
                    .environmentObject(environments)
                }
                .onMove(perform: legacyMoveProfile)
                .onDelete(perform: legacyDeleteProfile)
            }
        }

        private var legacyNormalList: some View {
            List {
                ForEach(profileList, id: \.id) { profile in
                    LegacyProfilePickerRow(
                        profile: profile,
                        isSelected: profile.id == selectedProfileID,
                        alert: $alert,
                        onSelect: {
                            selectedProfileID = profile.id
                            dismiss()
                        },
                        onEdit: {
                            profileToEdit = profile.origin
                        },
                        onUpdate: {
                            await updateProfile(profile)
                        }
                    )
                    .environmentObject(environments)
                }
            }
        }

        private func legacyMoveProfile(from source: IndexSet, to destination: Int) {
            profileList.move(fromOffsets: source, toOffset: destination)
            for (index, profile) in profileList.enumerated() {
                profileList[index].order = UInt32(index)
                profile.origin.order = UInt32(index)
            }
            Task {
                do {
                    try await ProfileManager.update(profileList.map(\.origin))
                    environments.profileUpdate.send()
                } catch {
                    // Handle error silently
                }
            }
        }

        private func legacyDeleteProfile(at offsets: IndexSet) {
            let profilesToDelete = offsets.map { profileList[$0].origin }
            profileList.remove(atOffsets: offsets)
            Task {
                do {
                    _ = try await ProfileManager.delete(profilesToDelete)
                    environments.emptyProfiles = profileList.isEmpty
                    environments.profileUpdate.send()
                } catch {
                    // Handle error silently
                }
            }
        }


    private func updateProfile(_ profile: ProfilePreview) async {
        do {
            try await profile.origin.updateRemoteProfile()
            environments.profileUpdate.send()
        } catch {
            alert = AlertState(action: "update remote profile", error: error)
        }
    }

    /// The remote configurations this page can fetch.
    private var remoteProfiles: [ProfilePreview] {
        profileList.filter { $0.type == .remote }
    }

    /// Fetch every remote configuration.
    ///
    /// The same call a single row makes, once per remote configuration. It reports progress
    /// through the page's own state, so the rows say what is happening rather than the page
    /// going quiet for as long as the slowest download takes.
    private func updateAllProfiles() async {
        guard !isUpdatingAll else {
            return
        }
        isUpdatingAll = true
        defer { isUpdatingAll = false }
        for profile in remoteProfiles {
            await updateProfile(profile)
        }
    }

    private func moveProfile(from source: IndexSet, to destination: Int) {
        profileList.move(fromOffsets: source, toOffset: destination)
        for (index, profile) in profileList.enumerated() {
            profileList[index].order = UInt32(index)
            profile.origin.order = UInt32(index)
        }
        Task {
            do {
                try await ProfileManager.update(profileList.map(\.origin))
                environments.profileUpdate.send()
            } catch {
                // Handle error silently
            }
        }
    }

    private func deleteProfile(at offsets: IndexSet) {
        let profilesToDelete = offsets.map { profileList[$0].origin }
        profileList.remove(atOffsets: offsets)
        Task {
            do {
                _ = try await ProfileManager.delete(profilesToDelete)
                environments.emptyProfiles = profileList.isEmpty
                environments.profileUpdate.send()
            } catch {
                // Handle error silently
            }
        }
    }

}

// MARK: - HakoProfilePickerRow

private struct HakoProfilePickerRow: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @Environment(\.locale) private var locale
        @Environment(\.editMode) private var editMode

    let profile: ProfilePreview
    let isSelected: Bool
    @Binding var alert: AlertState?
    let onSelect: () -> Void
    let onEdit: () -> Void
    let onUpdate: () async -> Void

        private var isEditing: Bool {
            editMode?.wrappedValue.isEditing ?? false
        }

    @State private var isUpdating = false
    @State private var showQRCode = false
    @State private var showQRSShare = false
    @State private var qrsShareData: Data?
        @State private var exportDocument: ProfileAnyExportDocument?
        @State private var showExporter = false

    var body: some View {
            defaultBody
    }


        @ViewBuilder
        private var defaultBody: some View {
                iOSBody
        }


            private var iOSBody: some View {
                Button {
                    if !isEditing, !isUpdating {
                        onSelect()
                    }
                } label: {
                    rowContent
                        // The same floor a first-level destination row has, so the
                        // configuration list and the menu it is opened from have one rhythm.
                        .frame(minHeight: HakoTheme.Layout.destinationRowTargetHeight)
                }
                .buttonStyle(.plain)
                .disabled(isEditing || isUpdating)
                .sheet(isPresented: $showQRCode) {
                    if let remoteURL = profile.remoteURL {
                        QRCodeSheet(profileName: profile.name, remoteURL: remoteURL)
                    }
                }
                .sheet(
                    isPresented: $showQRSShare,
                    onDismiss: {
                        qrsShareData = nil
                    },
                    content: {
                        if let data = qrsShareData {
                            HakoQRSSheet(profileName: profile.name, profileData: data)
                        } else {
                            ProgressView()
                        }
                    }
                )
                .fileExporter(
                    isPresented: $showExporter,
                    document: exportDocument,
                    contentType: exportDocument?.contentType ?? .data,
                    defaultFilename: exportDocument?.filename
                ) { result in
                    exportDocument = nil
                    if case let .failure(error) = result {
                        alert = AlertState(action: "export profile", error: error)
                    }
                }
            }

        private var rowContent: some View {
            HStack(spacing: HakoTheme.Spacing.row) {

                // The type is what a profile row has to say about itself, so it gets the icon
                // tile the rest of the client uses for "where does this live". The previous
                // leading checkmark said whether the row was selected, which the trailing mark
                // now says without occupying the position that carries information.
                // The first-level icon well, at the first-level size. It was the smaller
                // proxy-group well with a hand-set glyph, which is why the configuration list
                // read as a more compact species of list than the menu it is reached from - the
                // review's "raise the configuration centre's rows and icons to the first-level
                // standard".
                // The review's item: the type icon was indigo, cyan or teal - one colour per
                // kind of profile - which made a list of identically shaped rows read as four
                // categories. The kind is already said in words beside it; the icon is the
                // client's neutral one, like every other row's.
                HakoIconWell(tint: HakoAccentRole.neutral.color, systemImage: profile.type.presentationSymbol)

                VStack(alignment: .leading, spacing: HakoTheme.Typography.rowSubtitleGap(locale)) {
                    Text(profile.name)
                        .font(.body)
                        .foregroundStyle(.primary)
                        .lineLimit(1)

                    profileInfo
                }

                Spacer(minLength: HakoTheme.Spacing.compact)

                if !isEditing {
                    selectionMark
                }

                    if !isEditing {
                        rowMenu
                    }
            }
            .padding(HakoTheme.Spacing.standard)
            .cardStyle()
            .contentShape(Rectangle())
        }

        /// Whether this is the profile the client is using.
        private var selectionMark: some View {
            HakoSelectionMark(isSelected: isSelected)
        }

    private var rowMenu: some View {
        Menu {
            Button {
                onEdit()
            } label: {
                Label("Edit", systemImage: "pencil")
            }

            if profile.type == .remote {
                Button {
                    isUpdating = true
                    Task {
                        await onUpdate()
                        isUpdating = false
                    }
                } label: {
                    Label("Update", systemImage: "arrow.clockwise")
                }
            }

                shareMenu
        } label: {
            Group {
                if isUpdating {
                    ProgressView()
                        .scaleEffect(0.8)
                } else {
                    Image(systemName: "ellipsis")
                        .font(.system(size: 16))
                        .foregroundStyle(.secondary)
                }
            }
            .frame(width: 32, height: 32)
            .contentShape(Rectangle())
        }
        .buttonStyle(.plain)
    }

    private func prepareQRSShare() {
        qrsShareData = nil
        showQRSShare = true
        Task {
            do {
                let data = try await profile.origin.encodedContentDataAsync()
                await MainActor.run {
                    qrsShareData = data
                }
            } catch {
                await MainActor.run {
                    alert = AlertState(action: "prepare QRS share", error: error)
                    showQRSShare = false
                }
            }
        }
    }

        private var shareMenu: some View {
            Menu {
                    Button {
                        exportProfile(type: .file)
                    } label: {
                        Label("Save File", systemImage: "square.and.arrow.down")
                    }

                    ShareButtonCompat($alert) {
                        Label("Share File", systemImage: "doc")
                    } itemURL: {
                        try await profile.origin.generateShareFileAsync()
                    }

                    Button {
                        exportProfile(type: .json)
                    } label: {
                        Label("Save Content JSON", systemImage: "square.and.arrow.down")
                    }

                    ShareButtonCompat($alert) {
                        Label("Share Content JSON File", systemImage: "curlybraces")
                    } itemURL: {
                        try await profile.origin.generateJSONShareFileAsync(name: "\(profile.name).json")
                    }

                if profile.type == .remote {
                    Button {
                        showQRCode = true
                    } label: {
                        Label("Share URL as QR Code", systemImage: "qrcode")
                    }
                }

                Button {
                    prepareQRSShare()
                } label: {
                    Label("Share as QRS Code", systemImage: "barcode")
                }
            } label: {
                Label("Share", systemImage: "square.and.arrow.up")
            }
        }

        private func exportProfile(type: ExportItemType) {
            Task {
                do {
                    let document: ProfileAnyExportDocument
                    switch type {
                    case .file:
                        let data = try await profile.origin.encodedContentDataAsync()
                        document = ProfileAnyExportDocument(data: data, filename: "\(profile.name).bpf", contentType: .data)
                    case .json:
                        let content = try await profile.origin.readAsync()
                        document = ProfileAnyExportDocument(data: Data(content.utf8), filename: "\(profile.name).json", contentType: .json)
                    }
                    await MainActor.run {
                        exportDocument = document
                        showExporter = true
                    }
                } catch {
                    await MainActor.run {
                        alert = AlertState(action: "export profile", error: error)
                    }
                }
            }
        }

    private var profileInfo: some View {
        HStack(spacing: 8) {
            HStack(spacing: 4) {
                Image(systemName: profile.type.presentationSymbol)
                    .font(.system(size: 12))
                    .foregroundStyle(.secondary)
                Text(profile.type.presentationLabel)
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
            .layoutPriority(1)

            remainingTrafficInfo

            if profile.type == .remote, let lastUpdated = profile.lastUpdated {
                HStack(spacing: 4) {
                    Image(systemName: "clock.fill")
                        .font(.system(size: 12))
                        .foregroundStyle(.secondary)
                    Text(lastUpdated.relativeFormat(forPickerRow: locale))
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                }
                .layoutPriority(1)
            }
        }
        // The three items are one line's worth of information, so when they do not all fit they
        // give way together rather than one of them wrapping to a second line. That wrap is what
        // makes the English row tall: split across two lines, "Remote" and "6 days ago" take the
        // card from 106pt to 154pt, where a slightly smaller second line costs nothing but a
        // little size and keeps every item whole. The two items that were already on this line
        // keep their width first - they are why the line exists - and the quota gives way.
        .lineLimit(1)
        .minimumScaleFactor(0.8)
    }

    /// The panel's remaining quota, beside the type and the last update it belongs with.
    ///
    /// The row already carries this value: `ProfilePreview` mirrors `subscriptionInfo`, so the
    /// list reads it from the snapshot it holds rather than reaching back to `origin`.
    ///
    /// No quota reported means no item at all. `remainingBytes` is `nil` when the panel never
    /// sent a total - "unknown", which is not the same claim as a remainder of zero - so the row
    /// keeps saying only what it knows.
    ///
    /// It is text alone rather than `icon + text`, which is what the other two items on this line
    /// are. The line does not hold a fourth element at this width: measured on the iPhone 17,
    /// "Remote  clock 6 days ago" fills it, and adding an icon beside this item pushes the
    /// *relative time* - the item that was already here - onto a second line, taking the card
    /// from 106pt to 154pt for every remote row. The glyph was dropped so the two items that were
    /// already on the line keep the layout they had. The unit in the text says what the number
    /// is, so nothing is lost but the ornament.
    ///
    /// The word comes from this row's own `"%@ left"` entry rather than from the catalog's existing
    /// `"Available"`. That key is a standalone state label on three other pages (a Tailscale exit
    /// node, a Tailscale SSH row, and the remote server's own status), so shortening it would
    /// change what those pages say. "Available" is also five characters wider than the "可用" this
    /// line was laid out for, which is the whole of the English overflow. `"%@ left"` is scoped to
    /// this line, and its Chinese translation is the same "可用" the line has always shown.
    @ViewBuilder
    private var remainingTrafficInfo: some View {
        if let remainingBytes = profile.subscriptionInfo?.remainingBytes {
            Text(verbatim: String(format: String(localized: "%@ left"), Int64.remainingTrafficText(remainingBytes)))
                .font(.caption)
                .foregroundStyle(.secondary)
                .lineLimit(1)
                .minimumScaleFactor(0.8)
        }
    }

}

// MARK: - Export Helpers

    private enum ExportItemType {
        case file
        case json
    }

// MARK: - macOS Helpers


// MARK: - Legacy iOS HakoProfilePickerRow (iOS < 26)

    private struct LegacyProfilePickerRow: View {
        @EnvironmentObject private var environments: ExtensionEnvironments
        @Environment(\.editMode) private var editMode

        let profile: ProfilePreview
        let isSelected: Bool
        @Binding var alert: AlertState?
        let onSelect: () -> Void
        let onEdit: () -> Void
        let onUpdate: () async -> Void

        private var isEditing: Bool {
            editMode?.wrappedValue.isEditing ?? false
        }

        @State private var isUpdating = false
        @State private var showQRCode = false
        @State private var showQRSShare = false
        @State private var qrsShareData: Data?
        @State private var exportDocument: ProfileAnyExportDocument?
        @State private var showExporter = false

        var body: some View {
            Group {
                if isEditing {
                    editingBody
                } else {
                    normalBody
                }
            }
            .transaction { $0.animation = nil }
        }

        private var editingBody: some View {
            HStack(spacing: 12) {
                VStack(alignment: .leading, spacing: 4) {
                    Text(profile.name)
                        .font(.body)
                        .foregroundStyle(.primary)
                    profileInfo
                }
                Spacer()
            }
        }

        private var normalBody: some View {
            HStack(spacing: 12) {
                Button {
                    if !isUpdating {
                        onSelect()
                    }
                } label: {
                    HStack(spacing: 12) {
                        Image(systemName: "checkmark")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundStyle(.tint)
                            .opacity(isSelected ? 1 : 0)

                        VStack(alignment: .leading, spacing: 4) {
                            Text(profile.name)
                                .font(.body)
                                .foregroundStyle(.primary)
                            profileInfo
                        }
                    }
                }
                .buttonStyle(.plain)
                .disabled(isUpdating)

                Spacer()

                rowMenu
            }
            .sheet(isPresented: $showQRCode) {
                if let remoteURL = profile.remoteURL {
                    QRCodeSheet(profileName: profile.name, remoteURL: remoteURL)
                }
            }
            .sheet(
                isPresented: $showQRSShare,
                onDismiss: {
                    qrsShareData = nil
                },
                content: {
                    if let data = qrsShareData {
                        HakoQRSSheet(profileName: profile.name, profileData: data)
                    } else {
                        ProgressView()
                    }
                }
            )
            .fileExporter(
                isPresented: $showExporter,
                document: exportDocument,
                contentType: exportDocument?.contentType ?? .data,
                defaultFilename: exportDocument?.filename
            ) { result in
                exportDocument = nil
                if case let .failure(error) = result {
                    alert = AlertState(action: "export profile", error: error)
                }
            }
        }

        private var rowMenu: some View {
            Menu {
                Button {
                    onEdit()
                } label: {
                    Label("Edit", systemImage: "pencil")
                }

                if profile.type == .remote {
                    Button {
                        isUpdating = true
                        Task {
                            await onUpdate()
                            isUpdating = false
                        }
                    } label: {
                        Label("Update", systemImage: "arrow.clockwise")
                    }
                }

                shareMenu
            } label: {
                Group {
                    if isUpdating {
                        ProgressView()
                            .scaleEffect(0.8)
                    } else {
                        Image(systemName: "ellipsis")
                            .font(.system(size: 16))
                            .foregroundStyle(.secondary)
                    }
                }
                .frame(width: 32, height: 32)
                .contentShape(Rectangle())
            }
            .buttonStyle(.plain)
        }

        private func prepareQRSShare() {
            qrsShareData = nil
            showQRSShare = true
            Task {
                do {
                    let data = try await profile.origin.encodedContentDataAsync()
                    await MainActor.run {
                        qrsShareData = data
                    }
                } catch {
                    await MainActor.run {
                        alert = AlertState(action: "prepare QRS share", error: error)
                        showQRSShare = false
                    }
                }
            }
        }

        private var shareMenu: some View {
            Menu {
                Button {
                    exportProfile(type: .file)
                } label: {
                    Label("Save File", systemImage: "square.and.arrow.down")
                }

                ShareButtonCompat($alert) {
                    Label("Share File", systemImage: "doc")
                } itemURL: {
                    try await profile.origin.generateShareFileAsync()
                }

                Button {
                    exportProfile(type: .json)
                } label: {
                    Label("Save Content JSON", systemImage: "square.and.arrow.down")
                }

                ShareButtonCompat($alert) {
                    Label("Share Content JSON File", systemImage: "curlybraces")
                } itemURL: {
                    try await profile.origin.generateJSONShareFileAsync(name: "\(profile.name).json")
                }

                if profile.type == .remote {
                    Button {
                        showQRCode = true
                    } label: {
                        Label("Share URL as QR Code", systemImage: "qrcode")
                    }
                }

                Button {
                    prepareQRSShare()
                } label: {
                    Label("Share as QRS Code", systemImage: "barcode")
                }
            } label: {
                Label("Share", systemImage: "square.and.arrow.up")
            }
        }

        private func exportProfile(type: ExportItemType) {
            Task {
                do {
                    let document: ProfileAnyExportDocument
                    switch type {
                    case .file:
                        let data = try await profile.origin.encodedContentDataAsync()
                        document = ProfileAnyExportDocument(data: data, filename: "\(profile.name).bpf", contentType: .data)
                    case .json:
                        let content = try await profile.origin.readAsync()
                        document = ProfileAnyExportDocument(data: Data(content.utf8), filename: "\(profile.name).json", contentType: .json)
                    }
                    await MainActor.run {
                        exportDocument = document
                        showExporter = true
                    }
                } catch {
                    await MainActor.run {
                        alert = AlertState(action: "export profile", error: error)
                    }
                }
            }
        }

        private var profileInfo: some View {
            HStack(spacing: 8) {
                HStack(spacing: 4) {
                    Image(systemName: profile.type.presentationSymbol)
                        .font(.system(size: 12))
                        .foregroundStyle(.secondary)
                    Text(profile.type.presentationLabel)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                remainingTrafficInfo

                if profile.type == .remote, let lastUpdated = profile.lastUpdated {
                    HStack(spacing: 4) {
                        Image(systemName: "clock.fill")
                            .font(.system(size: 12))
                            .foregroundStyle(.secondary)
                        Text(lastUpdated.relativeFormat)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }
            }
        }

        /// The same item as the current row's, on the pre-26 layout.
        ///
        /// `remainingTrafficInfo` is declared inside `HakoProfilePickerRow`, a different type, so this
        /// row needs its own copy. Both read the same snapshot value.
        @ViewBuilder
        private var remainingTrafficInfo: some View {
            if let remainingBytes = profile.subscriptionInfo?.remainingBytes {
                Text(verbatim: String(format: String(localized: "%@ left"), Int64.remainingTrafficText(remainingBytes)))
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
                    .minimumScaleFactor(0.8)
            }
        }
    }

// MARK: - Remaining traffic presentation

private extension Int64 {
    /// A quota remainder as the configuration row spells it.
    ///
    /// Written here rather than taken from `ByteCountFormatter`: that formatter spells units out
    /// in full for several locales and returns "Zero KB" for nothing at all, and neither fits a
    /// caption that shares its line with two other items. The units are the decimal ones the
    /// panels themselves report against.
    ///
    /// - Zero is "0 B", not "0 GB": a remainder of nothing is a real value the row must state.
    /// - A negative value cannot reach here - `remainingBytes` clamps at zero - but is clamped
    ///   anyway so the caption can never read "-1 GB".
    /// - Precision is one decimal below ten and none from ten up: "1.2 TB" and "8.6 GB" keep
    ///   their shape, while ordinary quotas stay short - "286 GB", "840 MB".
    static func remainingTrafficText(_ bytes: Int64) -> String {
        // `Swift.max`, not `max`: the file's imports bring a `max` of their own, which the
        // `bytes` parameter would otherwise be handed to.
        let bytes = Swift.max(0, bytes)
        guard bytes >= 1000 else {
            return "\(bytes) B"
        }
        // Descending, so the first threshold the remainder clears is its unit.
        let units: [(threshold: Int64, divisor: Double, name: String)] = [
            (1_000_000_000_000, 1_000_000_000_000, "TB"),
            (1_000_000_000, 1_000_000_000, "GB"),
            (1_000_000, 1_000_000, "MB"),
            (1000, 1000, "KB"),
        ]
        let unit = units.first { bytes >= $0.threshold }!
        // Quantised at the one decimal the caption ever shows, so a value that rounds up to ten
        // is counted in tens and spelled "10 GB" rather than "10.0 GB".
        let rounded = (Double(bytes) / unit.divisor * 10).rounded() / 10
        let decimals = rounded < 10 ? 1 : 0
        return "\(rounded.formatted(.number.precision(.fractionLength(decimals)))) \(unit.name)"
    }
}

// MARK: - Relative time, at one line's width

// iOS only: the row that asks for this is the iOS-current one. The macOS and tvOS rows keep
// `relativeFormat` exactly as it was, so their width is not touched by a change made for a line
// they do not have.
    private extension Date {
        /// How long ago this was, sized for a configuration row's second line.
        ///
        /// `relativeFormat` spells the unit out - "6 days ago", "3 hours ago" - which is right where
        /// it has a line to itself, as on the home card, and too wide here: this line already carries
        /// the type, the remaining quota and this timestamp, and English spells all three longer than
        /// the Chinese the layout was drawn for. At the full style "6 days ago" measures 92.7pt
        /// against "6天前"'s 43.7pt, and the line is about 236pt wide - what was left went to the two
        /// items that were already there, and the quota had nowhere to go.
        ///
        /// So the unit is abbreviated where that is what makes it fit. Chinese keeps the full style,
        /// because its line already fits and "6天前" is what this row has always said; English reads
        /// "6d ago" instead of "6 days ago".
        ///
        /// - Parameter locale: the row's locale. A `RelativeDateTimeFormatter` defaults to the
        ///   current locale rather than to the one the view is rendered in, so it is passed in.
        func relativeFormat(forPickerRow locale: Locale) -> String {
            // Only languages whose unit is a separate word get shorter from abbreviation; Chinese
            // writes 天/小时/分钟, which an abbreviated style leaves as it is.
            guard !locale.identifier.hasPrefix("zh") else {
                return relativeFormat
            }
            let formatter = RelativeDateTimeFormatter()
            formatter.locale = locale
            formatter.unitsStyle = .abbreviated
            formatter.dateTimeStyle = .numeric
            return formatter.localizedString(for: self, relativeTo: Date())
        }
    }
