//
//  HakoProfileActionToolbar.swift
//  ApplicationLibrary
//
//  The phone's copy of `ApplicationLibrary/Views/Profile/ProfileActionToolbar.swift`, from `hako-ui` @ `c1935cf`.
//
//  A copy rather than an edit, because that file is upstream's and an iPad or a Mac loads it
//  too. Every module-scope type it declares is renamed into the Hako namespace and the phone's
//  own call sites are redirected here; nothing about its drawing, spacing, strings or behaviour
//  is changed.
//
//  Generated by `scripts/dev/migrate_secondary_page.py`. Re-run that rather than editing here.
//

import Libbox
import Library
import SwiftUI

@MainActor
public struct HakoProfileActionToolbar: View {
    @EnvironmentObject private var environments: ExtensionEnvironments
    @Environment(\.dismiss) private var dismiss


    @ObservedObject private var profile: Profile
    @ObservedObject private var viewModel: EditProfileViewModel

    public init(profile: Profile, viewModel: EditProfileViewModel) {
        self.profile = profile
        self.viewModel = viewModel
    }

    public var body: some View {

            iosBody


    }


        private var iosBody: some View {
            Section("Action") {
                if profile.type != .remote {
                    FormNavigationLink {
                        EditProfileContentView(EditProfileContentView.Context(profileID: profile.id!, readOnly: false))
                    } label: {
                        Label("Edit Content", systemImage: "pencil")
                            .foregroundColor(.accentColor)
                    }
                } else {
                    FormNavigationLink {
                        EditProfileContentView(EditProfileContentView.Context(profileID: profile.id!, readOnly: true))
                    } label: {
                        Label("View Content", systemImage: "doc.fill")
                            .foregroundColor(.accentColor)
                    }
                }
            }
        }


}
