#!/usr/bin/env python3
"""Build `HakoProfilePickerSheet.swift` from the picker the phone already had.

Reads the fork's picker from **this checkout** - `ApplicationLibrary/Views/Dashboard/Cards/ProfilePickerSheet.swift`
is upstream's file on the integration branch, and the fork's version with the quota row comes from the
**fork clone** at `DSH_REPO` (the one with an `origin/hako-ui` remote). The two are different
repositories, so both paths are needed.

The transform resolves the file's conditional compilation for `os(iOS) == true` and renames the two
types the phone owns. Resolving, rather than deleting `#if os(macOS)` spans, is the point: those usually
come with an `#else` the non-macOS build actually uses, and deleting the `#if` span leaves the `#else`
body dangling. A condition the evaluator cannot resolve is a failure rather than a guess.

Re-run this after an upstream sync rather than editing the generated file, or the next run will
disagree with it.
"""
import io
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GIT = os.environ.get("DSH_GIT") or "git"
ROOT = os.path.dirname(os.path.dirname(HERE))
REPO = os.environ.get("DSH_REPO") or os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(HERE))), "sing-box-for-apple")
SRC = os.path.join(ROOT, "ApplicationLibrary", "Views", "Dashboard", "Cards", "ProfilePickerSheet.swift")
DST = os.path.join(ROOT, "ApplicationLibrary", "Views", "HakoStyle", "HakoProfilePickerSheet.swift")

PLATFORM = {
    "os(iOS)": True,
    "os(macOS)": False,
    "os(tvOS)": False,
    "os(watchOS)": False,
    "os(visionOS)": False,
    "canImport(AppKit)": False,
    "canImport(UIKit)": True,
    "JAILBREAK": False,
    "DEBUG": False,
}

HEADER = '''//
//  HakoProfilePickerSheet.swift
//  ApplicationLibrary
//
//  The phone's configuration centre.
//
//  # Where this comes from
//
//  This is the fork's profile picker, from `hako-ui` @ `c1935cf`, resolved for iOS. It is the file
//  that carries the remaining-quota row: the item that reads the panel's `subscription-userinfo`
//  remainder out of the `ProfilePreview` snapshot the row already holds and prints it between the
//  configuration's type and its last-update time.
//
//  # Why it is a separate file from `ProfilePickerSheet`
//
//  An iPad and a Mac can both open the profile picker, and the requirement for both is upstream's
//  presentation with nothing added. The remaining-quota row is phone presentation. One file cannot
//  be both byte-identical to upstream and carry a new row, so
//  `ApplicationLibrary/Views/Dashboard/Cards/ProfilePickerSheet.swift` is restored to upstream and
//  this owns the phone's version.
//
//  The **data** chain is not forked: `SubscriptionInfo`, `RemoteProfileFetcher`,
//  `RemoteProfileRefresh`, `RemoteRefreshApplier` and the `add_subscription_info` migration are
//  shared, covered by `Tests/HakoSubscriptionUsage`, and read here through
//  `ProfilePreview.subscriptionInfo`.
//
//  # What is different from the official picker
//
//  The quota presentation, and the two layout properties that make room for it on the row's second
//  line. Everything else - the list, its edit mode, reorder, delete, QR share, export, and the editor
//  it presents - is upstream's, which is why this file is generated from the picker rather than
//  written out again. See `docs/HAKO-UI-MIGRATION-MATRIX.md`.
//
//  Generated by `scripts/dev/make_hako_profile_picker.py`, which is the only thing that should write
//  it.
//

'''

DIRECTIVE = re.compile(r"^([ \t]*)#(if|elseif|else|endif)\b[ \t]*(.*?)[ \t]*$")


def evaluate(condition: str) -> bool:
    """Resolve a Swift compilation condition for an iOS build.

    Supports what this file uses: a platform predicate, its negation written either as `!` or as
    `!os(...)` inside parentheses, and `||` / `&&` combinations. Anything else raises, because a
    condition the evaluator does not understand must not be guessed - guessing picks a branch, and
    picking the wrong branch produces a file that compiles into something nobody wrote.
    """
    text = condition.strip()

    # Rewrite the leaf predicates into Python booleans, longest key first so `os(iOS)` is not matched
    # inside a longer name.
    for key in sorted(PLATFORM, key=len, reverse=True):
        value = "True" if PLATFORM[key] else "False"
        text = text.replace(key, value)

    # `||` and `&&` share Python's meaning; `!` does not, so it is rewritten before evaluation.
    text = text.replace("||", " or ").replace("&&", " and ")
    text = re.sub(r"!\s*(True|False)", lambda m: "False" if m.group(1) == "True" else "True", text)

    # A bare `!` would be a Swift operator the rewrite above did not reach, which means a predicate
    # shape this evaluator does not know.
    if "!" in text:
        raise ValueError(f"cannot resolve condition: {condition!r}")

    # What may remain: the booleans this evaluator wrote, the operators, and parentheses. Anything
    # else is a condition that is not a platform fact - `swift(>=5.7)`, `arch(arm64)`, a custom flag -
    # and those are not guessed. The booleans are removed from the text before the identifier scan,
    # because `True` is itself made of letters and an earlier revision of this function rejected its
    # own output for that reason.
    residue = text
    for token in ("True", "False", " or ", " and ", "(", ")"):
        residue = residue.replace(token, " ")
    if re.search(r"[A-Za-z_0-9]", residue):
        raise ValueError(f"cannot resolve condition: {condition!r} (unresolved: {residue.strip()!r})")
    return bool(eval(text, {"__builtins__": {}}, {}))  # noqa: S307 - the text is digits and booleans


def resolve_for_ios(source: str) -> str:
    """Keep the branch an iOS build would compile, and drop the rest.

    Line-oriented rather than regex-span-based: a `#if` block's body is every line until the matching
    `#else`/`#elseif`/`#endif`, so the structure is a stack of frames and the output is built as it
    walks. That is what keeps an `#else` body attached to its `#if` instead of becoming orphaned text.
    """
    out: list[str] = []
    # Each frame: (any_branch_taken_yet, current_branch_active)
    stack: list[list[bool]] = []

    def active() -> bool:
        return all(frame[1] for frame in stack)

    for line in source.split("\n"):
        match = DIRECTIVE.match(line)
        if not match:
            if active():
                out.append(line)
            continue

        indent, kind, rest = match.group(1), match.group(2), match.group(3)

        if kind == "if":
            taken = evaluate(rest)
            stack.append([taken, taken])
        elif kind == "elseif":
            if not stack:
                raise ValueError("#elseif without #if")
            frame = stack[-1]
            if not frame[0]:
                frame[1] = evaluate(rest)
                frame[0] = frame[1]
            else:
                frame[1] = False
        elif kind == "else":
            if not stack:
                raise ValueError("#else without #if")
            frame = stack[-1]
            frame[1] = not frame[0]
            frame[0] = True
        elif kind == "endif":
            if not stack:
                raise ValueError("#endif without #if")
            stack.pop()

        # The directive line itself is not emitted: the branch it selected is inline now.
        _ = indent

    if stack:
        raise ValueError(f"{len(stack)} unterminated #if block(s)")
    return "\n".join(out)


def read_source() -> str:
    """The fork's picker, from the fork clone.

    This file is upstream's on the integration branch - the quota row was moved out of it - so the
    input is the fork's blob rather than the working tree. Read through git show, so the reference is
    a commit and not whatever a checkout happens to contain.
    """
    proc = subprocess.run(
        [GIT, "-C", REPO, "show", "origin/hako-ui:ApplicationLibrary/Views/Dashboard/Cards/ProfilePickerSheet.swift"],
        capture_output=True)
    if proc.returncode != 0:
        raise SystemExit(f"cannot read the fork's picker from {REPO}: "
                         f"{proc.stderr.decode('utf-8', 'replace').strip()}")
    return proc.stdout.decode("utf-8", "replace")


def main() -> int:
    regenerate = "--regenerate" in sys.argv
    src = read_source()

    declared_sheet = len(re.findall(
        r"^\s*(?:private\s+|public\s+|internal\s+)?struct\s+ProfilePickerSheet\b", src, re.M))
    declared_rows = len(re.findall(
        r"^\s*(?:private\s+|public\s+|internal\s+)?struct\s+\w*ProfilePickerRow\b", src, re.M))
    if declared_sheet != 1 or declared_rows != 2:
        print(f"FAILED: expected 1 ProfilePickerSheet and 2 ProfilePickerRow declarations; "
              f"found {declared_sheet} and {declared_rows}", file=sys.stderr)
        return 1

    resolved = resolve_for_ios(src)
    out, n_sheet = re.subn(r"\bProfilePickerSheet\b", "HakoProfilePickerSheet", resolved)
    out, n_row = re.subn(r"\bProfilePickerRow\b", "HakoProfilePickerRow", out)
    print(f"  renamed {n_sheet} ProfilePickerSheet and {n_row} ProfilePickerRow references")

    # `import AppKit` was inside the dropped branch; make sure it is gone and nothing else is.
    if re.search(r"^import AppKit$", out, re.M):
        print("FAILED: import AppKit survived the iOS resolution", file=sys.stderr)
        return 1
    out = re.sub(r"\n{4,}", "\n\n\n", out)
    out = HEADER + out

    if out.count("{") != out.count("}"):
        print(f"FAILED: braces unbalanced ({out.count('{')} vs {out.count('}')})", file=sys.stderr)
        return 1
    if re.search(r"^[ \t]*#(if|else|elseif|endif)\b", out, re.M):
        print("FAILED: a preprocessor directive survived the resolution", file=sys.stderr)
        return 1

    if os.path.exists(DST) and not regenerate:
        current = io.open(DST, encoding="utf-8").read()
        if current != out:
            print(f"FAILED: {os.path.relpath(DST, ROOT)} differs from what this script would write.",
                  file=sys.stderr)
            print("        Pass --regenerate to overwrite (only when the source changed).",
                  file=sys.stderr)
            return 1
        print(f"unchanged: {os.path.relpath(DST, ROOT)}")
        return 0

    io.open(DST, "w", encoding="utf-8", newline="").write(out)
    print(f"wrote {os.path.relpath(DST, ROOT)}: {len(out.splitlines())} lines "
          f"(source {len(src.splitlines())}, resolved {len(resolved.splitlines())})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
